// Tamil Master Vocabulary Database
// Last updated: 2026-02-13
// Total words: 248

const data = [
    {id:1, en:"Morning", ta:"Kaalai", pron:"Kaa-lai", cat:"Time"},
    {id:2, en:"Afternoon", ta:"Madhiyam", pron:"Ma-dhe-ya-im", cat:"Time"},
    {id:3, en:"Evening", ta:"Maalai", pron:"Maa-lai Saaingalam", cat:"Time"},
    {id:4, en:"Night", ta:"Rathiri", pron:"Raath-ree", cat:"Time"},
    {id:5, en:"Good Morning", ta:"Kaalai Vanakkam", pron:"", cat:"Time"},
    {id:6, en:"Good Afternoon", ta:"Madhiyam Vanakkam", pron:"", cat:"Time"},
    {id:7, en:"Good Evening", ta:"Maalai Vanakkam", pron:"", cat:"Time"},
    {id:8, en:"Good night", ta:"Rathiri Vanakkam", pron:"", cat:"Time"},
    {id:9, en:"Breakfast", ta:"Kaalai Saapadu", pron:"food", cat:"Time/Food"},
    {id:10, en:"Lunch", ta:"Madhiyam Sapadu", pron:"", cat:"Time/Food"},
    {id:11, en:"Dinner", ta:"Rathiri Sapadu", pron:"", cat:"Time/Food"},
    {id:12, en:"Father", ta:"Appa", pron:"Aa-ip-paa", cat:"Family"},
    {id:13, en:"Mother", ta:"Amma", pron:"Aa-im-maa", cat:"Family"},
    {id:14, en:"Grandfather", ta:"Thatha", pron:"Thaa-ith-tha", cat:"Family"},
    {id:15, en:"Grandmother", ta:"Paati", pron:"Paa-it-tea", cat:"Family"},
    {id:16, en:"Older brother", ta:"Anna", pron:"Aa-in-naa", cat:"Family"},
    {id:17, en:"Older sister", ta:"Akka", pron:"Aa-ik-kaa", cat:"Family"},
    {id:18, en:"Younger brother", ta:"Thumbi", pron:"Thumb--bee", cat:"Family"},
    {id:19, en:"Younger sister", ta:"Thangachi", pron:"Thaa-nga-ga-chee", cat:"Family"},
    {id:20, en:"Uncle", ta:"Mama", pron:"Maa-im-ma", cat:"Family"},
    {id:21, en:"Aunty", ta:"Maami / Athai", pron:"Maa-mee / aa-ith-ai", cat:"Family"},
    {id:22, en:"Husband", ta:"Kanavan", pron:"Ka-na-va-in / Purushan", cat:"Family"},
    {id:23, en:"Wife", ta:"Manaivi", pron:"Maa-nai-vee / Pondatii", cat:"Family"},
    {id:24, en:"Father's older brother - Big Dad", ta:"Periyaappa", pron:"PeriyaAmma", cat:"Family-Extended"},
    {id:25, en:"Father's younger brother - Small Dad", ta:"Chithappa (ChinnaAppa)", pron:"ChinnaAmma (Chithi)", cat:"Family-Extended"},
    {id:26, en:"Father's younger sister - Small Aunty", ta:"Chinnaathai", pron:"ChinnaMama", cat:"Family-Extended"},
    {id:27, en:"Father's older sister - Big Aunty", ta:"Periyaathai", pron:"PeriyaMama", cat:"Family-Extended"},
    {id:28, en:"Mother's older brother - Big Uncle", ta:"PeriyaMama", pron:"PeriyaAthai", cat:"Family-Extended"},
    {id:29, en:"Mother's younger brother - Small Uncle", ta:"ChinnaMama", pron:"ChinnaAthai", cat:"Family-Extended"},
    {id:30, en:"Mother's younger sister - Small Mom", ta:"ChinnaAmma (Chithi)", pron:"ChinnaAppa - Chithappa", cat:"Family-Extended"},
    {id:31, en:"Mother's older sister - Big Mom", ta:"PeriyaAmma", pron:"PeriyaAppa", cat:"Family-Extended"},
    {id:32, en:"What", ta:"Yenna", pron:"Ye-in-na", cat:"Question Word"},
    {id:33, en:"When", ta:"Yeppo", pron:"Yup-po", cat:"Question Word"},
    {id:34, en:"Where", ta:"Yenga", pron:"Ye-ing-ga", cat:"Question Word"},
    {id:35, en:"Who", ta:"Yaaru", pron:"Yaa-roo", cat:"Question Word"},
    {id:36, en:"Why", ta:"Yaen", pron:"Yae-in", cat:"Question Word"},
    {id:37, en:"How", ta:"Eppadi", pron:"Yup-pa-di", cat:"Question Word"},
    {id:38, en:"How many", ta:"Yethana", pron:"Ye-ith-tha-na", cat:"Question Word"},
    {id:39, en:"How much", ta:"Yevlo", pron:"Ye-iv-lo", cat:"Question Word"},
    {id:40, en:"From where", ta:"Yenga Irundhu", pron:"Ye-ing-ga Ee-ru-indh-uu", cat:"Question Word"},
    {id:41, en:"For what", ta:"Yethuku/Yethukaga", pron:"Ye-thu-ku / Ye-thu-ka-ga", cat:"Question Word"},
    {id:42, en:"Which", ta:"Yethu", pron:"Ye-thu", cat:"Question Word"},
    {id:43, en:"Whose", ta:"Yaarodathu", pron:"Yaa-ro-da-thu", cat:"Question Word"},
    {id:44, en:"I", ta:"Naan", pron:"Naa-in", cat:"Pronoun"},
    {id:45, en:"You", ta:"Neenga", pron:"Nee-ing-ga", cat:"Pronoun"},
    {id:46, en:"He", ta:"Avaru", pron:"Aa-va-ru", cat:"Pronoun"},
    {id:47, en:"She/They", ta:"Avanga", pron:"Aa-vang-ga", cat:"Pronoun"},
    {id:48, en:"We - Including Listener", ta:"Namma", pron:"Na-im-ma", cat:"Pronoun"},
    {id:49, en:"We - Excluding Listener", ta:"Naanga", pron:"Naa-ing-ga", cat:"Pronoun"},
    {id:50, en:"I (Past - Irundh)", ta:"Irundhan", pron:"", cat:"Verb Conjugation"},
    {id:51, en:"I (Present - Iruk)", ta:"Irukan", pron:"", cat:"Verb Conjugation"},
    {id:52, en:"I (Future - Irup)", ta:"Irupan", pron:"", cat:"Verb Conjugation"},
    {id:53, en:"You (Past - Irundh)", ta:"Irundheenga", pron:"", cat:"Verb Conjugation"},
    {id:54, en:"You (Present - Iruk)", ta:"Irukeenga", pron:"", cat:"Verb Conjugation"},
    {id:55, en:"You (Future - Irup)", ta:"Irupeenga", pron:"", cat:"Verb Conjugation"},
    {id:56, en:"He (Past - Irundh)", ta:"Irundharu", pron:"", cat:"Verb Conjugation"},
    {id:57, en:"He (Present - Iruk)", ta:"Irukaru", pron:"", cat:"Verb Conjugation"},
    {id:58, en:"He (Future - Irup)", ta:"Iruparu", pron:"", cat:"Verb Conjugation"},
    {id:59, en:"She/They (Past - Irundh)", ta:"Irundhanga", pron:"", cat:"Verb Conjugation"},
    {id:60, en:"She/They (Present - Iruk)", ta:"Irukanga", pron:"", cat:"Verb Conjugation"},
    {id:61, en:"She/They (Future - Irup)", ta:"Irupanga", pron:"", cat:"Verb Conjugation"},
    {id:62, en:"We (Inc.) (Past - Irundh)", ta:"Irundhom", pron:"", cat:"Verb Conjugation"},
    {id:63, en:"We (Inc.) (Present - Iruk)", ta:"Irukom", pron:"", cat:"Verb Conjugation"},
    {id:64, en:"We (Inc.) (Future - Irup)", ta:"Irupom", pron:"", cat:"Verb Conjugation"},
    {id:65, en:"We (Exc.) (Past - Irundh)", ta:"Irundhom", pron:"", cat:"Verb Conjugation"},
    {id:66, en:"We (Exc.) (Present - Iruk)", ta:"Irukom", pron:"", cat:"Verb Conjugation"},
    {id:67, en:"We (Exc.) (Future - Irup)", ta:"Irupom", pron:"", cat:"Verb Conjugation"},
    {id:68, en:"Non Humans (Past - Irundh)", ta:"Irundhuchu", pron:"", cat:"Verb Conjugation"},
    {id:69, en:"Non Humans (Present - Iruk)", ta:"Iruku", pron:"", cat:"Verb Conjugation"},
    {id:70, en:"Non Humans (Future - Irup)", ta:"Irukum", pron:"", cat:"Verb Conjugation"},
    {id:71, en:"My", ta:"Ennoda / En", pron:"", cat:"Possessive"},
    {id:72, en:"Your", ta:"Ungaloda / Unga", pron:"", cat:"Possessive"},
    {id:73, en:"His", ta:"Avaroda", pron:"", cat:"Possessive"},
    {id:74, en:"Her/Their", ta:"Avangaloda", pron:"", cat:"Possessive"},
    {id:75, en:"Our", ta:"Nammaloda", pron:"", cat:"Possessive"},
    {id:76, en:"Us (Our - Exc.)", ta:"Engaloda", pron:"", cat:"Possessive"},
    {id:79, en:"I (Past /?)", ta:"Irundhana?", pron:"", cat:"Question Conjugation"},
    {id:80, en:"You (Past /?)", ta:"Irundheengala?", pron:"", cat:"Question Conjugation"},
    {id:81, en:"He (Past /?)", ta:"Irundhara?", pron:"", cat:"Question Conjugation"},
    {id:82, en:"She/They (Past /?)", ta:"Irundhangala?", pron:"", cat:"Question Conjugation"},
    {id:83, en:"We (Past /?)", ta:"Irundhoma?", pron:"", cat:"Question Conjugation"},
    {id:84, en:"Non Humans (Past /?)", ta:"Irundhucha?", pron:"", cat:"Question Conjugation"},
    {id:85, en:"I (Present /?)", ta:"Irukana?", pron:"", cat:"Question Conjugation"},
    {id:86, en:"You (Present /?)", ta:"Irukeengala?", pron:"", cat:"Question Conjugation"},
    {id:87, en:"He (Present /?)", ta:"Irukara?", pron:"", cat:"Question Conjugation"},
    {id:88, en:"She/They (Present /?)", ta:"Irukangala?", pron:"", cat:"Question Conjugation"},
    {id:89, en:"We (Present /?)", ta:"Irukoma?", pron:"", cat:"Question Conjugation"},
    {id:90, en:"Non Humans (Present /?)", ta:"Iruka?", pron:"", cat:"Question Conjugation"},
    {id:91, en:"I (Future /?)", ta:"Irupana?", pron:"", cat:"Question Conjugation"},
    {id:92, en:"You (Future /?)", ta:"Irupeengala?", pron:"", cat:"Question Conjugation"},
    {id:93, en:"He (Future /?)", ta:"Irupara?", pron:"", cat:"Question Conjugation"},
    {id:94, en:"She/They (Future /?)", ta:"Irupangala?", pron:"", cat:"Question Conjugation"},
    {id:95, en:"We (Future /?)", ta:"Irupoma?", pron:"", cat:"Question Conjugation"},
    {id:96, en:"Non Humans (Future /?)", ta:"Irukuma?", pron:"", cat:"Question Conjugation"},
    {id:97, en:"Father (/?)", ta:"Appa-va?", pron:"", cat:"Family-Question"},
    {id:98, en:"Mother (/?)", ta:"Amma-va?", pron:"", cat:"Family-Question"},
    {id:99, en:"Grandfather (/?)", ta:"Thatha-va?", pron:"", cat:"Family-Question"},
    {id:100, en:"Grandmother (/?)", ta:"Paati-ya?", pron:"", cat:"Family-Question"},
    {id:101, en:"Older brother (/?)", ta:"Anna-va?", pron:"", cat:"Family-Question"},
    {id:102, en:"Older sister (/?)", ta:"Akka-va?", pron:"", cat:"Family-Question"},
    {id:103, en:"Younger brother (/?)", ta:"Thumbi-ya?", pron:"", cat:"Family-Question"},
    {id:104, en:"Younger sister (/?)", ta:"Thungachi-ya?", pron:"", cat:"Family-Question"},
    {id:105, en:"Uncle (/?)", ta:"Mama-va?", pron:"", cat:"Family-Question"},
    {id:106, en:"Aunty (/?)", ta:"Maami-ya? Athai-ya?", pron:"", cat:"Family-Question"},
    {id:107, en:"Husband (/?)", ta:"Kanava-ah? Purushana?", pron:"", cat:"Family-Question"},
    {id:108, en:"Wife (/?)", ta:"Manaivi-ya? Pondatii-ya?", pron:"", cat:"Family-Question"},
    {id:109, en:"Boy/Son", ta:"Paiyan", pron:"Paa-ai-ya-in", cat:"People"},
    {id:110, en:"Girl/Daughter", ta:"Ponnu", pron:"Poo-in-nu", cat:"People"},
    {id:111, en:"Up/Above/On/Upstairs", ta:"Maela", pron:"MAY-le", cat:"Location/Adverb"},
    {id:112, en:"Below/Under/Down/Downstairs", ta:"Keela", pron:"KEY-le", cat:"Location/Adverb"},
    {id:113, en:"Front/Before/Infront", ta:"Munnadi", pron:"MU-naddi", cat:"Location/Adverb"},
    {id:114, en:"Back/After/Behind", ta:"Pinnadi", pron:"PI-naddi", cat:"Location/Adverb"},
    {id:115, en:"Small", ta:"Chinnathu/Chinna", pron:"CHIN-ath-e / Che-in-na", cat:"Adjective"},
    {id:116, en:"Big", ta:"Perusu/Periya", pron:"Pae-ree-ya / Pe-ru-su", cat:"Adjective"},
    {id:117, en:"Little/Less", ta:"Konjam / Kammi", pron:"Koo-in-jam / Kaa-im-me", cat:"Quantity"},
    {id:118, en:"More/Very/A lot", ta:"Neraiya/Romba", pron:"NE-ray-uh / RUUM-ba", cat:"Quantity"},
    {id:119, en:"Many", ta:"Adhigam", pron:"UH-di-gum", cat:"Quantity"},
    {id:120, en:"This", ta:"Idhu / Indha", pron:"", cat:"Demonstrative"},
    {id:121, en:"That", ta:"Adhu / Andha", pron:"", cat:"Demonstrative"},
    {id:122, en:"Here", ta:"Inga", pron:"", cat:"Location"},
    {id:123, en:"There", ta:"Anga", pron:"", cat:"Location"},
    {id:124, en:"Now", ta:"Ippo", pron:"", cat:"Time"},
    {id:125, en:"Then/while/during", ta:"Appo", pron:"", cat:"Time"},
    {id:126, en:"Like this", ta:"Indha Mathiri / Ippadi", pron:"", cat:"Manner"},
    {id:127, en:"Like that", ta:"Andha Mathiri / Appadi", pron:"", cat:"Manner"},
    {id:128, en:"Truth", ta:"Unmai", pron:"", cat:"Abstract"},
    {id:129, en:"Lie", ta:"Poi", pron:"", cat:"Abstract"},
    {id:130, en:"Correct/Right/Okay", ta:"Sari", pron:"Cherry", cat:"Abstract"},
    {id:131, en:"Wrong/mistake", ta:"Thappu", pron:"", cat:"Abstract"},
    {id:132, en:"Bitter", ta:"Kasapu", pron:"", cat:"Taste"},
    {id:133, en:"Sweet", ta:"Inipu", pron:"", cat:"Taste"},
    {id:134, en:"Sour", ta:"Pulipu", pron:"", cat:"Taste"},
    {id:135, en:"Salt", ta:"Uppu", pron:"", cat:"Taste"},
    {id:136, en:"Tart", ta:"Thuvarpu", pron:"", cat:"Taste"},
    {id:137, en:"Spicy", ta:"Kaaram", pron:"", cat:"Taste"},
    {id:138, en:"Inside", ta:"Ulla", pron:"", cat:"Location"},
    {id:139, en:"Outside", ta:"Veliya", pron:"", cat:"Location"},
    {id:140, en:"Old", ta:"Palaya/Palasu", pron:"", cat:"Adjective"},
    {id:141, en:"New", ta:"Pudhu/Pudhusu", pron:"", cat:"Adjective"},
    {id:142, en:"Yesterday", ta:"Nethu", pron:"", cat:"Time"},
    {id:143, en:"Today", ta:"Inaiku", pron:"", cat:"Time"},
    {id:144, en:"Tomorrow", ta:"Naalaiku", pron:"", cat:"Time"},
    {id:145, en:"House", ta:"Veedu", pron:"", cat:"Noun"},
    {id:146, en:"In the House", ta:"Veetla", pron:"", cat:"Noun"},
    {id:147, en:"To the House", ta:"Veetuku", pron:"", cat:"Noun"},
    {id:148, en:"Yes", ta:"Aama", pron:"", cat:"Affirmation/Negation"},
    {id:149, en:"No/Not/Not there/Neither/Either/Or", ta:"illa", pron:"", cat:"Affirmation/Negation"},
    {id:150, en:"But", ta:"Aana", pron:"", cat:"Conjunction"},
    {id:151, en:"Because", ta:"Yaena", pron:"", cat:"Conjunction"},
    {id:152, en:"And/After", ta:"Apram", pron:"", cat:"Conjunction/Time"},
    {id:153, en:"Name/People", ta:"Peru", pron:"", cat:"Noun"},
    {id:154, en:"To me", ta:"Enaku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:155, en:"To you", ta:"Ungaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:156, en:"To him", ta:"Avaruku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:157, en:"To her/them", ta:"Avangaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:158, en:"To us (Inc.)", ta:"Nammaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:159, en:"To us (Exc.)", ta:"Engaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:162, en:"With me", ta:"Enkitta", pron:"", cat:"Non Personal Pronoun"},
    {id:163, en:"With you", ta:"Ungakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:164, en:"With him", ta:"Avarukitta", pron:"", cat:"Non Personal Pronoun"},
    {id:165, en:"With her/them", ta:"Avangakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:166, en:"With us (Inc.)", ta:"Nammakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:167, en:"With us (Exc.)", ta:"Engakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:172, en:"Like (+ /?)", ta:"Pudikuma?", pron:"", cat:"Verb - Present Cont."},
    {id:173, en:"Like (- /?)", ta:"Pudikatha?", pron:"", cat:"Verb - Present Cont."},
    {id:174, en:"Want (+)", ta:"Venum", pron:"Ve-nu-im", cat:"Verb"},
    {id:175, en:"Want (-)", ta:"Vendam", pron:"Ve-in-da-im", cat:"Verb"},
    {id:176, en:"Want (+ /?)", ta:"Venuma?", pron:"", cat:"Verb"},
    {id:177, en:"Want (- /?)", ta:"Vendama?", pron:"", cat:"Verb"},
    {id:181, en:"Understand (- /?)", ta:"Puriyatha?", pron:"", cat:"Verb - Present Cont."},
    {id:184, en:"Know (+ /?)", ta:"Theriyuma?", pron:"", cat:"Verb - Present Cont."},
    {id:185, en:"Know (- /?)", ta:"Theriyatha?", pron:"", cat:"Verb - Present Cont."},
    {id:186, en:"Enough (Quantity)", ta:"Podhum", pron:"Po-dhu-im", cat:"Quantity"},
    {id:187, en:"Enough (Measurement)", ta:"Pathum", pron:"Pa-ith-um", cat:"Quantity"},
    {id:188, en:"Enough (Quantity -)", ta:"Podhathu", pron:"Po-dha-thu", cat:"Quantity"},
    {id:189, en:"Enough (Measurement -)", ta:"Pathathu", pron:"Pa-ith-tha-thu", cat:"Quantity"},
    {id:190, en:"Enough (Quantity /?)", ta:"Podhuma?", pron:"", cat:"Quantity"},
    {id:191, en:"Enough (Measurement /?)", ta:"Pathuma?", pron:"", cat:"Quantity"},
    {id:192, en:"Enough (Quantity - /?)", ta:"Podhatha?", pron:"", cat:"Quantity"},
    {id:193, en:"Enough (Measurement - /?)", ta:"Pathatha?", pron:"", cat:"Quantity"},
    {id:194, en:"Didn't Like", ta:"Pudikala", pron:"", cat:"Verb - Past Negative"},
    {id:195, en:"Didn't know", ta:"Therila", pron:"", cat:"Verb - Past Negative"},
    {id:196, en:"Didn't understand", ta:"Purila", pron:"", cat:"Verb - Past Negative"},
    {id:197, en:"Didn't Like (/?)", ta:"Pudikalaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:198, en:"Didn't know (/?)", ta:"Therilaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:199, en:"Didn't understand (/?)", ta:"Purilaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:200, en:"In/at", ta:"la", pron:"", cat:"Postposition"},
    {id:201, en:"With", ta:"Kuda", pron:"", cat:"Postposition"},
    {id:202, en:"Without", ta:"illama", pron:"", cat:"Postposition"},
    {id:203, en:"For", ta:"Kaga", pron:"", cat:"Postposition"},
    {id:204, en:"About", ta:"Pathi", pron:"", cat:"Postposition"},
    {id:205, en:"Because of", ta:"Naela", pron:"", cat:"Postposition"},
    {id:206, en:"Inside", ta:"Ulla", pron:"", cat:"Postposition"},
    {id:207, en:"Outside", ta:"Veliya", pron:"", cat:"Postposition"},
    {id:208, en:"To - Inside", ta:"Ku", pron:"", cat:"Postposition"},
    {id:209, en:"To - Nearby", ta:"Kitta", pron:"", cat:"Postposition"},
    {id:210, en:"On", ta:"Maela", pron:"", cat:"Postposition"},
    {id:211, en:"If", ta:"na", pron:"", cat:"Conjunction"},
    {id:212, en:"From", ta:"Irundhu", pron:"", cat:"Postposition"},
    {id:213, en:"Under", ta:"Keezhla", pron:"", cat:"Postposition"},
    {id:214, en:"Front", ta:"Munnadi", pron:"", cat:"Postposition"},
    {id:215, en:"Back", ta:"Pinnadi", pron:"", cat:"Postposition"},
    {id:216, en:"Liked (Past)", ta:"Pudichithu", pron:"", cat:"Verb - Like"},
    {id:217, en:"Liked (Past /?)", ta:"Pudichitha?", pron:"", cat:"Verb - Like"},
    {id:218, en:"Liking - Instant (Present)", ta:"Pudichiruku", pron:"", cat:"Verb - Like"},
    {id:219, en:"Liking - Instant (Present /?)", ta:"Pudichiruka?", pron:"", cat:"Verb - Like"},
    {id:220, en:"Like - Cont (Present)", ta:"Pudikum", pron:"", cat:"Verb - Like"},
    {id:221, en:"Like - Cont (Present /?)", ta:"Pudikuma?", pron:"", cat:"Verb - Like"},
    {id:222, en:"Understood (Past)", ta:"Purinjuthu", pron:"", cat:"Verb - Understand"},
    {id:223, en:"Understood (Past /?)", ta:"Purinjutha?", pron:"", cat:"Verb - Understand"},
    {id:224, en:"Understand (Present - Instant)", ta:"Puriyuthu", pron:"", cat:"Verb - Understand"},
    {id:225, en:"Understand (Present - Instant /?)", ta:"Puriyutha?", pron:"", cat:"Verb - Understand"},
    {id:226, en:"Understand (Present - Cont)", ta:"Puriyum", pron:"", cat:"Verb - Understand"},
    {id:227, en:"Understand (Present - Cont /?)", ta:"Puriyuma?", pron:"", cat:"Verb - Understand"},
    {id:228, en:"I knew [saw] (Past)", ta:"Therinjuthu", pron:"", cat:"Verb - Know"},
    {id:229, en:"I knew [saw] (Past /?)", ta:"Therinjutha?", pron:"", cat:"Verb - Know"},
    {id:230, en:"Know (Present - Instant)", ta:"Theriyuthu", pron:"", cat:"Verb - Know"},
    {id:231, en:"Know (Present - Instant /?)", ta:"Theriyutha?", pron:"", cat:"Verb - Know"},
    {id:232, en:"Know (Present - Cont)", ta:"Theriyum", pron:"", cat:"Verb - Know"},
    {id:233, en:"Know (Present - Cont /?)", ta:"Theriyuma?", pron:"", cat:"Verb - Know"},
    {id:234, en:"Day before yesterday", ta:"Mundha Nethu", pron:"", cat:"Time"},
    {id:235, en:"Day after tomorrow", ta:"Naalanaiku", pron:"", cat:"Time"},
    {id:236, en:"Day", ta:"Naal", pron:"", cat:"Time"},
    {id:237, en:"Week", ta:"Vaaram", pron:"", cat:"Time"},
    {id:238, en:"Month", ta:"Maasam", pron:"", cat:"Time"},
    {id:239, en:"Year", ta:"Varusham", pron:"", cat:"Time"},
    {id:240, en:"Second", ta:"Nodi", pron:"", cat:"Time"},
    {id:241, en:"Minute", ta:"Nimisham", pron:"", cat:"Time"},
    {id:242, en:"Hour", ta:"Mani Neram", pron:"", cat:"Time"},
    {id:243, en:"Clock", ta:"Mani", pron:"", cat:"Time"},
    {id:244, en:"2 weeks before", ta:"2 weeks Munnadi", pron:"", cat:"Time"},
    {id:245, en:"2 months after", ta:"2 weeks apram", pron:"", cat:"Time"},
    {id:246, en:"Last week", ta:"Ponna Varam", pron:"", cat:"Time"},
    {id:247, en:"This week", ta:"Indha Varam", pron:"", cat:"Time"},
    {id:248, en:"Next week", ta:"Adutha Varam", pron:"", cat:"Time"},
    {id:249, en:"Indian Money", ta:"Rupees", pron:"", cat:"Noun"},
    {id:250, en:"1", ta:"Onnu", pron:"", cat:"Number"},
    {id:251, en:"2", ta:"Rendu", pron:"", cat:"Number"},
    {id:252, en:"3", ta:"Moonu", pron:"", cat:"Number"},
    {id:253, en:"4", ta:"Naalu", pron:"", cat:"Number"},
    {id:254, en:"5", ta:"Aanchu", pron:"", cat:"Number"},
    {id:255, en:"6", ta:"Aaru", pron:"", cat:"Number"},
    {id:256, en:"7", ta:"Yellu", pron:"", cat:"Number"},
    {id:257, en:"8", ta:"Yettu", pron:"", cat:"Number"},
    {id:258, en:"9", ta:"Onbathu", pron:"", cat:"Number"},
    {id:259, en:"10", ta:"Pathu", pron:"", cat:"Number"},
    {id:260, en:"11", ta:"Pathionnu", pron:"", cat:"Number"},
    {id:261, en:"12", ta:"Panandu", pron:"", cat:"Number"}
];

// Opposite pairs for matching game
// Total: 15 pairs
const oppositePairs = [
    [1, 4],     // Morning - Night
    [111, 112], // Up - Down
    [113, 114], // Front - Back
    [115, 116], // Small - Big
    [117, 118], // Less - More
    [120, 121], // This - That
    [122, 123], // Here - There
    [124, 125], // Now - Then
    [128, 129], // Truth - Lie
    [130, 131], // Right - Wrong
    [132, 133], // Bitter - Sweet
    [138, 139], // Inside - Outside
    [140, 141], // Old - New
    [142, 144], // Yesterday - Tomorrow
    [148, 149]  // Yes - No
];

// Sentence templates for fill-in-the-blank exercises
// IMPROVEMENTS:
// - Each sentence uses multiple vocabulary words from the data array for better context
// - 1-2 new words are introduced (wrapped in <mark> tags) to expand learning
// - Sentences demonstrate real usage patterns and word combinations
// - Use {word} as placeholder for the word to fill in
const sentenceTemplates = [
    // Time sentences
    {tamil: "Naan {word} appa-va <mark>paarthen</mark> (paaru)", english: "I <mark>saw</mark> father {word}", categories: ["Time"], exclude: ["Hour", "Minute", "Second", "Clock", "Week", "Month", "Year"]},
    {tamil: "Amma {word} veetla <mark>velai seiranga</mark> (seiya)", english: "Mother <mark>works</mark> at home in the {word}", categories: ["Time"], exclude: ["Hour", "Minute", "Second", "Clock", "Week", "Month", "Year", "Day"]},
    {tamil: "Enaku {word} saapadu romba pudikum", english: "I really like {word} food", categories: ["Time/Food"]},
    {tamil: "{word} romba <mark>seekiram</mark> poguthu", english: "The {word} is going very <mark>quickly</mark>", categories: ["Time"], exclude: ["Morning", "Afternoon", "Evening", "Night", "Breakfast", "Lunch", "Dinner"]},
    {tamil: "Indha {word} enaku romba <mark>mukkiyam</mark>", english: "This {word} is very <mark>important</mark> to me", categories: ["Time"], exclude: ["Morning", "Afternoon", "Evening", "Night"]},

    // Family sentences
    {tamil: "En {word} ippo veetla irukanga, aana apram <mark>veliya poganga</mark> (poga)", english: "My {word} is at home now, but later will <mark>go out</mark>", categories: ["Family", "Family-Extended"]},
    {tamil: "Naan en {word} kuda kaalai saapadu <mark>saapten</mark> (saapadu)", english: "I <mark>ate</mark> breakfast with my {word}", categories: ["Family", "Family-Extended"]},
    {tamil: "Ungaloda {word} yenga irukanga? Veetla irukanga <mark>illa</mark> veliya irukanga?", english: "Where is your {word}? At home <mark>or</mark> outside?", categories: ["Family", "Family-Extended"]},
    {tamil: "En {word} romba <mark>nalla</mark> per", english: "My {word} is a very <mark>good</mark> person", categories: ["Family"]},

    // Question words
    {tamil: "{word} <mark>pesuranga</mark> (pesu)? Appa <mark>pesurara</mark> (pesu) illa amma pesuranga?", english: "{word} is <mark>speaking</mark>? Is father <mark>speaking</mark> or mother?", categories: ["Question Word"]},
    {tamil: "Neenga {word} irundhu <mark>vandheenga</mark> (vara)? Chennai-la irundhu <mark>vandheengala</mark> (vara)?", english: "From {word} did you <mark>come</mark>? Did you <mark>come</mark> from Chennai?", categories: ["Question Word"]},
    {tamil: "{word} <mark>poganum</mark> (poga)? Ippo poganum illa naalaiku poganum?", english: "{word} should <mark>go</mark>? Should go now or tomorrow?", categories: ["Question Word"]},
    {tamil: "Idhu {word}? Enaku theriyatha, neenga <mark>sollunga</mark> (sollu)", english: "This is {word}? I don't know, you <mark>tell me</mark>", categories: ["Question Word"]},

    // Pronouns
    {tamil: "{word} nethu veetla saapadu <mark>saapten</mark> (saapadu), romba inipu", english: "{word} <mark>ate</mark> food at home yesterday, very sweet", categories: ["Pronoun"]},
    {tamil: "{word} ippo inga irukkom, naalaiku anga irupom", english: "{word} are here now, tomorrow will be there", categories: ["Pronoun"]},
    {tamil: "{word} inaiku veetuku <mark>poganum</mark> (poga), aana naalaiku <mark>theva illa</mark>", english: "{word} should <mark>go</mark> home today, but tomorrow <mark>no need</mark>", categories: ["Pronoun"]},

    // Possessives
    {tamil: "{word} veedu romba periya veedu, chinna veedu illa", english: "{word} house is a very big house, not a small house", categories: ["Possessive"]},
    {tamil: "{word} paiyan ippo anga veliya <mark>vilayadura</mark> (vilaiyaadu)", english: "{word} boy is now outside <mark>playing</mark>", categories: ["Possessive"]},
    {tamil: "Idhu {word} veedu, adhu avangaloda veedu", english: "This is {word} house, that is their house", categories: ["Possessive"]},

    // Location/Direction
    {tamil: "Saapadu {word} iruku, naan <mark>edukaren</mark> (edukka)", english: "The food is {word}, I will <mark>take it</mark>", categories: ["Location/Adverb"], exclude: ["Here", "There"]},
    {tamil: "Naan {word} <mark>paakuren</mark> (paaru), pinnadi paakala", english: "I am <mark>looking</mark> {word}, not looking back", categories: ["Location/Adverb"]},
    {tamil: "Appa {word} irukaru, naan keela irukken", english: "Father is {word}, I am below", categories: ["Location/Adverb"]},

    // Postposition - only for standalone words, not particles
    {tamil: "Amma veedu {word} <mark>poganga</mark> (poga), <mark>thirumbhi varuvanga</mark> (thirumbu + vara)", english: "Mother will <mark>go</mark> {word} the house, will <mark>return</mark>", categories: ["Postposition"], exclude: ["In/at", "To - Inside", "To - Nearby", "On", "Under"]},
    {tamil: "Naan appa {word} <mark>pesuren</mark> (pesu), romba <mark>sandhosham</mark>", english: "I'm <mark>talking</mark> {word} father, very <mark>happy</mark>", categories: ["Postposition"], exclude: ["In/at", "To - Inside", "To - Nearby", "On", "Under", "From"]},
    {tamil: "Neenga {word} <mark>vandheenga</mark> (vara), <mark>thaniya vandheenga</mark> (thaniya)?", english: "You <mark>came</mark> {word} (someone), or came <mark>alone</mark>?", categories: ["Postposition"], exclude: ["In/at", "To - Inside", "To - Nearby", "On", "Under", "From", "Inside", "Outside"]},

    // Adjectives
    {tamil: "Idhu romba {word} saapadu, enaku pudikum", english: "This is very {word} food, I like it", categories: ["Adjective", "Taste"]},
    {tamil: "En {word} veedu inga iruku, ungaloda pudhu veedu anga iruka?", english: "My {word} house is here, is your new house there?", categories: ["Adjective"]},
    {tamil: "Adhu {word} veedu illa, periya veedu", english: "That is not a {word} house, it's a big house", categories: ["Adjective"]},

    // Quantity
    {tamil: "Enaku {word} saapadu venum, adhigam vendam", english: "I want {word} food, don't want too much", categories: ["Quantity"]},
    {tamil: "{word} iruka? Illa, {word} illa, adhigam iruku", english: "Is there {word}? No, there's not {word}, there's a lot", categories: ["Quantity"]},
    {tamil: "Ippo {word} per irukanga, naalaiku neraiya per <mark>varuvanga</mark> (vara)", english: "Now there are {word} people, tomorrow many people will <mark>come</mark>", categories: ["Quantity"]},

    // Demonstrative
    {tamil: "{word} en veedu, adhu ungaloda veedu", english: "{word} is my house, that is your house", categories: ["Demonstrative"]},
    {tamil: "{word} veedu periya, aana andha veedu chinna", english: "{word} house is big, but that house is small", categories: ["Demonstrative"]},
    {tamil: "Naan {word} mathiri <mark>seiren</mark> (seiya), appa andha mathiri <mark>seiraru</mark> (seiya)", english: "I <mark>do</mark> like {word}, father <mark>does</mark> like that", categories: ["Demonstrative", "Manner"]},

    // Verbs - Like/Know/Understand
    {tamil: "Enaku {word}, ungaluku pudikuma?", english: "I {word}, do you like it?", categories: ["Verb - Like", "Verb - Present Cont."]},
    {tamil: "Ungaluku {word}? Enaku theriyum, romba <mark>easy</mark>", english: "Do you {word}? I know, very <mark>easy</mark>", categories: ["Verb - Know", "Verb - Present Cont."]},
    {tamil: "Naan nethu {word}, aana ippo <mark>puriyum</mark> (puriya)", english: "I {word} yesterday, but now I <mark>understand</mark>", categories: ["Verb - Past Negative"]},
    {tamil: "Enaku idhu {word}, aana adhu <mark>puriyatha</mark> (puriya-neg)", english: "I {word} this, but don't <mark>understand</mark> that", categories: ["Verb - Understand", "Verb - Know"]},

    // Want/Enough
    {tamil: "Enaku {word}, ungaluku venuma?", english: "I {word}, do you want?", categories: ["Verb"]},
    {tamil: "Idhu {word}? Aama, romba podhum", english: "Is this {word}? Yes, very enough", categories: ["Quantity"]},

    // Numbers
    {tamil: "Enaku {word} veedu venum, rendu veedu vendam", english: "I want {word} house(s), don't want two houses", categories: ["Number"]},
    {tamil: "Inga {word} per irukanga, anga moonu per irukanga", english: "Here there are {word} people, there are three people", categories: ["Number"]},
    {tamil: "Naalaiku {word} mani neram-la <mark>varen</mark> (vara)", english: "Tomorrow I will <mark>come</mark> at {word} o'clock", categories: ["Number"]},

    // Affirmation/Negation/Conjunction
    {tamil: "{word}, naan ippo <mark>pogiren</mark> (poga), naalaiku <mark>varuvren</mark> (vara)", english: "{word}, I am <mark>going</mark> now, will <mark>come</mark> tomorrow", categories: ["Affirmation/Negation"]},
    {tamil: "Naan <mark>vandhan</mark> (vara), {word} appa <mark>varala</mark> (vara-neg)", english: "I <mark>came</mark>, {word} father didn't <mark>come</mark>", categories: ["Conjunction"]},
    {tamil: "Idhu unmai {word} poi? Enaku <mark>theriyatha</mark> (theriya-neg)", english: "Is this truth {word} lie? I don't <mark>know</mark>", categories: ["Affirmation/Negation", "Abstract"]},
    {tamil: "Naan <mark>pogiren</mark> (poga) {word} neenga <mark>pogala</mark> (poga-neg)", english: "I am <mark>going</mark> {word} you are not <mark>going</mark>", categories: ["Conjunction"]},

    // Dative/Non-personal pronouns
    {tamil: "{word} pudikum, avarruku <mark>pudikatha</mark> (pudikka-neg)", english: "I like (to {word}), he doesn't like", categories: ["Personal Pronoun-Dative"]},
    {tamil: "{word} theriyum, avangaluku <mark>theriyatha</mark> (theriya-neg)", english: "I know (to {word}), they don't know", categories: ["Personal Pronoun-Dative"]},
    {tamil: "Naan {word} <mark>pesuren</mark> (pesu), avanga enkitta <mark>pesuranga</mark> (pesu)", english: "I'm <mark>talking</mark> {word}, they're <mark>talking</mark> with me", categories: ["Non Personal Pronoun"]},

    // People/Abstract
    {tamil: "Andha {word} veetla irukanga, veliya <mark>irukala</mark> (irukka-neg)", english: "That {word} is at home, not outside", categories: ["People", "Family"]},
    {tamil: "Idhu {word}, adhu thappu illa", english: "This is {word}, that is not wrong", categories: ["Abstract"]},
    {tamil: "En peru {word}, ungaloda peru yenna?", english: "My name is {word}, what is your name?", categories: ["Noun"]},

    // Nouns
    {tamil: "Naan {word} saapadu <mark>saapten</mark> (saapadu), romba inipu", english: "I <mark>ate</mark> {word} food, very sweet", categories: ["Noun", "Time/Food"]},
    {tamil: "Idhu {word}, adhu rupees", english: "This is {word}, that is rupees", categories: ["Noun"]},

    // Time-specific
    {tamil: "Naan {word} amma-va <mark>paarthen</mark> (paaru)", english: "I <mark>saw</mark> mother {word}", categories: ["Time"], exclude: ["Hour", "Minute", "Second", "Clock", "Week", "Month", "Year"]},
    {tamil: "{word} veedu <mark>pogalam</mark> (poga)", english: "Can <mark>go</mark> home {word}", categories: ["Time"], exclude: ["Hour", "Minute", "Second", "Clock", "Week", "Month", "Year", "Day"]},
    {tamil: "Indha {word} naan romba <mark>velai seiren</mark> (seiya)", english: "This {word} I <mark>work</mark> a lot", categories: ["Time"], exclude: ["Morning", "Afternoon", "Evening", "Night", "Hour", "Minute", "Second", "Clock", "Yesterday", "Today", "Tomorrow", "Breakfast", "Lunch", "Dinner"]},

    // Mixed complexity - use existing vocab conjugations
    {tamil: "Appa nethu irundhan, ippo {word}, naalaiku iruparu", english: "Father was yesterday, now {word}, tomorrow will be", categories: ["Verb Conjugation"]},
    {tamil: "{word} veetla irukanga? Aama, ippo veetla irukanga", english: "Is {word} at home? Yes, now at home", categories: ["Family-Question"]},
    {tamil: "Idhu {word} mathiri iruku, aana adhu <mark>vera mathiri</mark>", english: "This is like {word}, but that is <mark>different way</mark>", categories: ["Manner", "Demonstrative"]}
];
