// Tamil Master Vocabulary Database
// Last updated: 2026-02-07
// Total words: 261

const data = [
    {id:1, en:"Morning", ta:"Kaalai", pron:"Kaa-lai", cat:"Time"},
    {id:2, en:"Afternoon", ta:"Madhiyam", pron:"Ma-dhe-ya-im", cat:"Time"},
    {id:3, en:"Evening", ta:"Maalai", pron:"Maa-lai Saaingalam", cat:"Time"},
    {id:4, en:"Night", ta:"Rathiri", pron:"Raath-ree", cat:"Time"},
    {id:5, en:"Good Morning", ta:"Kaalai Vanakkam", pron:"", cat:"Time"},
    {id:6, en:"Good Afternoon", ta:"Madhiyam Vanakkam", pron:"", cat:"Time"},
    {id:7, en:"Good Evening", ta:"Maalai Vanakkam", pron:"", cat:"Time"},
    {id:8, en:"Good night", ta:"Rathiri Vanakkam", pron:"", cat:"Time"},
    {id:9, en:"Breakfast", ta:"Kaalai Saapadu", pron:"food", cat:"Time/Food"},
    {id:10, en:"Lunch", ta:"Madhiyam Sapadu", pron:"", cat:"Time/Food"},
    {id:11, en:"Dinner", ta:"Rathiri Sapadu", pron:"", cat:"Time/Food"},
    {id:12, en:"Father", ta:"Appa", pron:"Aa-ip-paa", cat:"Family"},
    {id:13, en:"Mother", ta:"Amma", pron:"Aa-im-maa", cat:"Family"},
    {id:14, en:"Grandfather", ta:"Thatha", pron:"Thaa-ith-tha", cat:"Family"},
    {id:15, en:"Grandmother", ta:"Paati", pron:"Paa-it-tea", cat:"Family"},
    {id:16, en:"Older brother", ta:"Anna", pron:"Aa-in-naa", cat:"Family"},
    {id:17, en:"Older sister", ta:"Akka", pron:"Aa-ik-kaa", cat:"Family"},
    {id:18, en:"Younger brother", ta:"Thumbi", pron:"Thumb--bee", cat:"Family"},
    {id:19, en:"Younger sister", ta:"Thangachi", pron:"Thaa-nga-ga-chee", cat:"Family"},
    {id:20, en:"Uncle", ta:"Mama", pron:"Maa-im-ma", cat:"Family"},
    {id:21, en:"Aunty", ta:"Maami / Athai", pron:"Maa-mee / aa-ith-ai", cat:"Family"},
    {id:22, en:"Husband", ta:"Kanavan", pron:"Ka-na-va-in / Purushan", cat:"Family"},
    {id:23, en:"Wife", ta:"Manaivi", pron:"Maa-nai-vee / Pondatii", cat:"Family"},
    {id:24, en:"Father's older brother - Big Dad", ta:"Periyaappa", pron:"PeriyaAmma", cat:"Family-Extended"},
    {id:25, en:"Father's younger brother - Small Dad", ta:"Chithappa (ChinnaAppa)", pron:"ChinnaAmma (Chithi)", cat:"Family-Extended"},
    {id:26, en:"Father's younger sister - Small Aunty", ta:"Chinnaathai", pron:"ChinnaMama", cat:"Family-Extended"},
    {id:27, en:"Father's older sister - Big Aunty", ta:"Periyaathai", pron:"PeriyaMama", cat:"Family-Extended"},
    {id:28, en:"Mother's older brother - Big Uncle", ta:"PeriyaMama", pron:"PeriyaAthai", cat:"Family-Extended"},
    {id:29, en:"Mother's younger brother - Small Uncle", ta:"ChinnaMama", pron:"ChinnaAthai", cat:"Family-Extended"},
    {id:30, en:"Mother's younger sister - Small Mom", ta:"ChinnaAmma (Chithi)", pron:"ChinnaAppa - Chithappa", cat:"Family-Extended"},
    {id:31, en:"Mother's older sister - Big Mom", ta:"PeriyaAmma", pron:"PeriyaAppa", cat:"Family-Extended"},
    {id:32, en:"What", ta:"Yenna", pron:"Ye-in-na", cat:"Question Word"},
    {id:33, en:"When", ta:"Yeppo", pron:"Yup-po", cat:"Question Word"},
    {id:34, en:"Where", ta:"Yenga", pron:"Ye-ing-ga", cat:"Question Word"},
    {id:35, en:"Who", ta:"Yaaru", pron:"Yaa-roo", cat:"Question Word"},
    {id:36, en:"Why", ta:"Yaen", pron:"Yae-in", cat:"Question Word"},
    {id:37, en:"How", ta:"Eppadi", pron:"Yup-pa-di", cat:"Question Word"},
    {id:38, en:"How many", ta:"Yethana", pron:"Ye-ith-tha-na", cat:"Question Word"},
    {id:39, en:"How much", ta:"Yevlo", pron:"Ye-iv-lo", cat:"Question Word"},
    {id:40, en:"From where", ta:"Yenga Irundhu", pron:"Ye-ing-ga Ee-ru-indh-uu", cat:"Question Word"},
    {id:41, en:"For what", ta:"Yethuku/Yethukaga", pron:"Ye-thu-ku / Ye-thu-ka-ga", cat:"Question Word"},
    {id:42, en:"Which", ta:"Yethu", pron:"Ye-thu", cat:"Question Word"},
    {id:43, en:"Whose", ta:"Yaarodathu", pron:"Yaa-ro-da-thu", cat:"Question Word"},
    {id:44, en:"I", ta:"Naan", pron:"Naa-in", cat:"Pronoun"},
    {id:45, en:"You", ta:"Neenga", pron:"Nee-ing-ga", cat:"Pronoun"},
    {id:46, en:"He", ta:"Avaru", pron:"Aa-va-ru", cat:"Pronoun"},
    {id:47, en:"She/They", ta:"Avanga", pron:"Aa-vang-ga", cat:"Pronoun"},
    {id:48, en:"We - Including Listener", ta:"Namma", pron:"Na-im-ma", cat:"Pronoun"},
    {id:49, en:"We - Excluding Listener", ta:"Naanga", pron:"Naa-ing-ga", cat:"Pronoun"},
    {id:50, en:"I (Past Tense - Irundh)", ta:"Irundhan", pron:"", cat:"Verb Conjugation"},
    {id:51, en:"I (Present Tense - Iruk)", ta:"Irukan", pron:"", cat:"Verb Conjugation"},
    {id:52, en:"I (Future Tense - Irup)", ta:"Irupan", pron:"", cat:"Verb Conjugation"},
    {id:53, en:"You (Past Tense - Irundh)", ta:"Irundheenga", pron:"", cat:"Verb Conjugation"},
    {id:54, en:"You (Present Tense - Iruk)", ta:"Irukeenga", pron:"", cat:"Verb Conjugation"},
    {id:55, en:"You (Future Tense - Irup)", ta:"Irupeenga", pron:"", cat:"Verb Conjugation"},
    {id:56, en:"He (Past Tense - Irundh)", ta:"Irundharu", pron:"", cat:"Verb Conjugation"},
    {id:57, en:"He (Present Tense - Iruk)", ta:"Irukaru", pron:"", cat:"Verb Conjugation"},
    {id:58, en:"He (Future Tense - Irup)", ta:"Iruparu", pron:"", cat:"Verb Conjugation"},
    {id:59, en:"She/They (Past Tense - Irundh)", ta:"Irundhanga", pron:"", cat:"Verb Conjugation"},
    {id:60, en:"She/They (Present Tense - Iruk)", ta:"Irukanga", pron:"", cat:"Verb Conjugation"},
    {id:61, en:"She/They (Future Tense - Irup)", ta:"Irupanga", pron:"", cat:"Verb Conjugation"},
    {id:62, en:"We (Inc.) (Past Tense - Irundh)", ta:"Irundhom", pron:"", cat:"Verb Conjugation"},
    {id:63, en:"We (Inc.) (Present Tense - Iruk)", ta:"Irukom", pron:"", cat:"Verb Conjugation"},
    {id:64, en:"We (Inc.) (Future Tense - Irup)", ta:"Irupom", pron:"", cat:"Verb Conjugation"},
    {id:65, en:"We (Exc.) (Past Tense - Irundh)", ta:"Irundhom", pron:"", cat:"Verb Conjugation"},
    {id:66, en:"We (Exc.) (Present Tense - Iruk)", ta:"Irukom", pron:"", cat:"Verb Conjugation"},
    {id:67, en:"We (Exc.) (Future Tense - Irup)", ta:"Irupom", pron:"", cat:"Verb Conjugation"},
    {id:68, en:"Non Humans (Past Tense - Irundh)", ta:"Irundhuchu", pron:"", cat:"Verb Conjugation"},
    {id:69, en:"Non Humans (Present Tense - Iruk)", ta:"Iruku", pron:"", cat:"Verb Conjugation"},
    {id:70, en:"Non Humans (Future Tense - Irup)", ta:"Irukum", pron:"", cat:"Verb Conjugation"},
    {id:71, en:"My", ta:"Ennoda / En", pron:"", cat:"Possessive"},
    {id:72, en:"Your", ta:"Ungaloda / Unga", pron:"", cat:"Possessive"},
    {id:73, en:"His", ta:"Avaroda", pron:"", cat:"Possessive"},
    {id:74, en:"Her/Their", ta:"Avangaloda", pron:"", cat:"Possessive"},
    {id:75, en:"Our", ta:"Nammaloda", pron:"", cat:"Possessive"},
    {id:76, en:"Us (Our - Exc.)", ta:"Engaloda", pron:"", cat:"Possessive"},
    {id:77, en:"Mother's", ta:"Amma'oda", pron:"", cat:"Possessive"},
    {id:78, en:"School's", ta:"School'oda", pron:"", cat:"Possessive"},
    {id:79, en:"I (Past Tense Question)", ta:"Irundhana?", pron:"", cat:"Question Conjugation"},
    {id:80, en:"You (Past Tense Question)", ta:"Irundheengala?", pron:"", cat:"Question Conjugation"},
    {id:81, en:"He (Past Tense Question)", ta:"Irundhara?", pron:"", cat:"Question Conjugation"},
    {id:82, en:"She/They (Past Tense Question)", ta:"Irundhangala?", pron:"", cat:"Question Conjugation"},
    {id:83, en:"We (Past Tense Question)", ta:"Irundhoma?", pron:"", cat:"Question Conjugation"},
    {id:84, en:"Non Humans (Past Tense Question)", ta:"Irundhucha?", pron:"", cat:"Question Conjugation"},
    {id:85, en:"I (Present Tense Question)", ta:"Irukana?", pron:"", cat:"Question Conjugation"},
    {id:86, en:"You (Present Tense Question)", ta:"Irukeengala?", pron:"", cat:"Question Conjugation"},
    {id:87, en:"He (Present Tense Question)", ta:"Irukara?", pron:"", cat:"Question Conjugation"},
    {id:88, en:"She/They (Present Tense Question)", ta:"Irukangala?", pron:"", cat:"Question Conjugation"},
    {id:89, en:"We (Present Tense Question)", ta:"Irukoma?", pron:"", cat:"Question Conjugation"},
    {id:90, en:"Non Humans (Present Tense Question)", ta:"Iruka?", pron:"", cat:"Question Conjugation"},
    {id:91, en:"I (Future Tense Question)", ta:"Irupana?", pron:"", cat:"Question Conjugation"},
    {id:92, en:"You (Future Tense Question)", ta:"Irupeengala?", pron:"", cat:"Question Conjugation"},
    {id:93, en:"He (Future Tense Question)", ta:"Irupara?", pron:"", cat:"Question Conjugation"},
    {id:94, en:"She/They (Future Tense Question)", ta:"Irupangala?", pron:"", cat:"Question Conjugation"},
    {id:95, en:"We (Future Tense Question)", ta:"Irupoma?", pron:"", cat:"Question Conjugation"},
    {id:96, en:"Non Humans (Future Tense Question)", ta:"Irukuma?", pron:"", cat:"Question Conjugation"},
    {id:97, en:"Father (Question)", ta:"Appa-va?", pron:"", cat:"Family-Question"},
    {id:98, en:"Mother (Question)", ta:"Amma-va?", pron:"", cat:"Family-Question"},
    {id:99, en:"Grandfather (Question)", ta:"Thatha-va?", pron:"", cat:"Family-Question"},
    {id:100, en:"Grandmother (Question)", ta:"Paati-ya?", pron:"", cat:"Family-Question"},
    {id:101, en:"Older brother (Question)", ta:"Anna-va?", pron:"", cat:"Family-Question"},
    {id:102, en:"Older sister (Question)", ta:"Akka-va?", pron:"", cat:"Family-Question"},
    {id:103, en:"Younger brother (Question)", ta:"Thumbi-ya?", pron:"", cat:"Family-Question"},
    {id:104, en:"Younger sister (Question)", ta:"Thungachi-ya?", pron:"", cat:"Family-Question"},
    {id:105, en:"Uncle (Question)", ta:"Mama-va?", pron:"", cat:"Family-Question"},
    {id:106, en:"Aunty (Question)", ta:"Maami-ya? Athai-ya?", pron:"", cat:"Family-Question"},
    {id:107, en:"Husband (Question)", ta:"Kanava-ah? Purushana?", pron:"", cat:"Family-Question"},
    {id:108, en:"Wife (Question)", ta:"Manaivi-ya? Pondatii-ya?", pron:"", cat:"Family-Question"},
    {id:109, en:"Boy/Son", ta:"Paiyan", pron:"Paa-ai-ya-in", cat:"People"},
    {id:110, en:"Girl/Daughter", ta:"Ponnu", pron:"Poo-in-nu", cat:"People"},
    {id:111, en:"Up/Above/On/Upstairs", ta:"Maela", pron:"MAY-le", cat:"Location/Adverb"},
    {id:112, en:"Below/Under/Down/Downstairs", ta:"Keela", pron:"KEY-le", cat:"Location/Adverb"},
    {id:113, en:"Front/Before/Infront", ta:"Munnadi", pron:"MU-naddi", cat:"Location/Adverb"},
    {id:114, en:"Back/After/Behind", ta:"Pinnadi", pron:"PI-naddi", cat:"Location/Adverb"},
    {id:115, en:"Small", ta:"Chinnathu/Chinna", pron:"CHIN-ath-e / Che-in-na", cat:"Adjective"},
    {id:116, en:"Big", ta:"Perusu/Periya", pron:"Pae-ree-ya / Pe-ru-su", cat:"Adjective"},
    {id:117, en:"Little/Less", ta:"Konjam / Kammi", pron:"Koo-in-jam / Kaa-im-me", cat:"Quantity"},
    {id:118, en:"More/Very/A lot", ta:"Neraiya/Romba", pron:"NE-ray-uh / RUUM-ba", cat:"Quantity"},
    {id:119, en:"Many", ta:"Adhigam", pron:"UH-di-gum", cat:"Quantity"},
    {id:120, en:"This", ta:"Idhu / Indha", pron:"", cat:"Demonstrative"},
    {id:121, en:"That", ta:"Adhu / Andha", pron:"", cat:"Demonstrative"},
    {id:122, en:"Here", ta:"Inga", pron:"", cat:"Location"},
    {id:123, en:"There", ta:"Anga", pron:"", cat:"Location"},
    {id:124, en:"Now", ta:"Ippo", pron:"", cat:"Time"},
    {id:125, en:"Then/while/during", ta:"Appo", pron:"", cat:"Time"},
    {id:126, en:"Like this", ta:"Indha Mathiri / Ippadi", pron:"", cat:"Manner"},
    {id:127, en:"Like that", ta:"Andha Mathiri / Appadi", pron:"", cat:"Manner"},
    {id:128, en:"Truth", ta:"Unmai", pron:"", cat:"Abstract"},
    {id:129, en:"Lie", ta:"Poi", pron:"", cat:"Abstract"},
    {id:130, en:"Correct/Right/Okay", ta:"Sari", pron:"Cherry", cat:"Abstract"},
    {id:131, en:"Wrong/mistake", ta:"Thappu", pron:"", cat:"Abstract"},
    {id:132, en:"Bitter", ta:"Kasapu", pron:"", cat:"Taste"},
    {id:133, en:"Sweet", ta:"Inipu", pron:"", cat:"Taste"},
    {id:134, en:"Sour", ta:"Pulipu", pron:"", cat:"Taste"},
    {id:135, en:"Salt", ta:"Uppu", pron:"", cat:"Taste"},
    {id:136, en:"Tart", ta:"Thuvarpu", pron:"", cat:"Taste"},
    {id:137, en:"Spicy", ta:"Kaaram", pron:"", cat:"Taste"},
    {id:138, en:"Inside", ta:"Ulla", pron:"", cat:"Location"},
    {id:139, en:"Outside", ta:"Veliya", pron:"", cat:"Location"},
    {id:140, en:"Old", ta:"Palaya/Palasu", pron:"", cat:"Adjective"},
    {id:141, en:"New", ta:"Pudhu/Pudhusu", pron:"", cat:"Adjective"},
    {id:142, en:"Yesterday", ta:"Nethu", pron:"", cat:"Time"},
    {id:143, en:"Today", ta:"Inaiku", pron:"", cat:"Time"},
    {id:144, en:"Tomorrow", ta:"Naalaiku", pron:"", cat:"Time"},
    {id:145, en:"House", ta:"Veedu", pron:"", cat:"Noun"},
    {id:146, en:"In the House", ta:"Veetla", pron:"", cat:"Noun"},
    {id:147, en:"To the House", ta:"Veetuku", pron:"", cat:"Noun"},
    {id:148, en:"Yes", ta:"Aama", pron:"", cat:"Affirmation/Negation"},
    {id:149, en:"No/Not/Not there/Neither/Either/Or", ta:"illa", pron:"", cat:"Affirmation/Negation"},
    {id:150, en:"But", ta:"Aana", pron:"", cat:"Conjunction"},
    {id:151, en:"Because", ta:"Yaena", pron:"", cat:"Conjunction"},
    {id:152, en:"And/After", ta:"Apram", pron:"", cat:"Conjunction/Time"},
    {id:153, en:"Name/People", ta:"Peru", pron:"", cat:"Noun"},
    {id:154, en:"To me", ta:"Enaku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:155, en:"To you", ta:"Ungaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:156, en:"To him", ta:"Avaruku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:157, en:"To her/them", ta:"Avangaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:158, en:"To us (Inc.)", ta:"Nammaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:159, en:"To us (Exc.)", ta:"Engaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:160, en:"To mom", ta:"Ammaku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:161, en:"To school", ta:"School'ku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:162, en:"With me", ta:"Enkitta", pron:"", cat:"Non Personal Pronoun"},
    {id:163, en:"With you", ta:"Ungakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:164, en:"With him", ta:"Avarukitta", pron:"", cat:"Non Personal Pronoun"},
    {id:165, en:"With her/them", ta:"Avangakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:166, en:"With us (Inc.)", ta:"Nammakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:167, en:"With us (Exc.)", ta:"Engakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:170, en:"Like (Positive)", ta:"Pudikum", pron:"Po-de-ku-im", cat:"Verb - Present Cont."},
    {id:171, en:"Like (Negative)", ta:"Pudikathu", pron:"Po-de-kaa-thu", cat:"Verb - Present Cont."},
    {id:172, en:"Like (Positive Question)", ta:"Pudikuma?", pron:"", cat:"Verb - Present Cont."},
    {id:173, en:"Like (Negative Question)", ta:"Pudikatha?", pron:"", cat:"Verb - Present Cont."},
    {id:174, en:"Want (Positive)", ta:"Venum", pron:"Ve-nu-im", cat:"Verb"},
    {id:175, en:"Want (Negative)", ta:"Vendam", pron:"Ve-in-da-im", cat:"Verb"},
    {id:176, en:"Want (Positive Question)", ta:"Venuma?", pron:"", cat:"Verb"},
    {id:177, en:"Want (Negative Question)", ta:"Vendama?", pron:"", cat:"Verb"},
    {id:178, en:"Understand (Positive)", ta:"Puriyum", pron:"Po-re-u-im", cat:"Verb - Present Cont."},
    {id:179, en:"Understand (Negative)", ta:"Puriyathu", pron:"Pu-re-ya-thu", cat:"Verb - Present Cont."},
    {id:180, en:"Understand (Positive Question)", ta:"Puriyuma?", pron:"", cat:"Verb - Present Cont."},
    {id:181, en:"Understand (Negative Question)", ta:"Puriyatha?", pron:"", cat:"Verb - Present Cont."},
    {id:182, en:"Know (Positive)", ta:"Theriyum", pron:"Thae-re-yum", cat:"Verb - Present Cont."},
    {id:183, en:"Know (Negative)", ta:"Theriyathu", pron:"Thae-re-ya-thu", cat:"Verb - Present Cont."},
    {id:184, en:"Know (Positive Question)", ta:"Theriyuma?", pron:"", cat:"Verb - Present Cont."},
    {id:185, en:"Know (Negative Question)", ta:"Theriyatha?", pron:"", cat:"Verb - Present Cont."},
    {id:186, en:"Enough (Quantity)", ta:"Podhum", pron:"Po-dhu-im", cat:"Quantity"},
    {id:187, en:"Enough (Measurement)", ta:"Pathum", pron:"Pa-ith-um", cat:"Quantity"},
    {id:188, en:"Enough (Quantity - Negative)", ta:"Podhathu", pron:"Po-dha-thu", cat:"Quantity"},
    {id:189, en:"Enough (Measurement - Negative)", ta:"Pathathu", pron:"Pa-ith-tha-thu", cat:"Quantity"},
    {id:190, en:"Enough (Quantity - Question)", ta:"Podhuma?", pron:"", cat:"Quantity"},
    {id:191, en:"Enough (Measurement - Question)", ta:"Pathuma?", pron:"", cat:"Quantity"},
    {id:192, en:"Enough (Quantity - Negative Question)", ta:"Podhatha?", pron:"", cat:"Quantity"},
    {id:193, en:"Enough (Measurement - Negative Question)", ta:"Pathatha?", pron:"", cat:"Quantity"},
    {id:194, en:"Didn't Like", ta:"Pudikala", pron:"", cat:"Verb - Past Negative"},
    {id:195, en:"Didn't know", ta:"Therila", pron:"", cat:"Verb - Past Negative"},
    {id:196, en:"Didn't understand", ta:"Purila", pron:"", cat:"Verb - Past Negative"},
    {id:197, en:"Didn't Like (Question)", ta:"Pudikalaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:198, en:"Didn't know (Question)", ta:"Therilaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:199, en:"Didn't understand (Question)", ta:"Purilaiya?", pron:"", cat:"Verb - Past Negative"},
    {id:200, en:"In/at", ta:"la", pron:"", cat:"Postposition"},
    {id:201, en:"With", ta:"Kuda", pron:"", cat:"Postposition"},
    {id:202, en:"Without", ta:"illama", pron:"", cat:"Postposition"},
    {id:203, en:"For", ta:"Kaga", pron:"", cat:"Postposition"},
    {id:204, en:"About", ta:"Pathi", pron:"", cat:"Postposition"},
    {id:205, en:"Because of", ta:"Naela", pron:"", cat:"Postposition"},
    {id:206, en:"Inside", ta:"Ulla", pron:"", cat:"Postposition"},
    {id:207, en:"Outside", ta:"Veliya", pron:"", cat:"Postposition"},
    {id:208, en:"To - Inside", ta:"Ku", pron:"", cat:"Postposition"},
    {id:209, en:"To - Nearby", ta:"Kitta", pron:"", cat:"Postposition"},
    {id:210, en:"On", ta:"Maela", pron:"", cat:"Postposition"},
    {id:211, en:"If", ta:"na", pron:"", cat:"Conjunction"},
    {id:212, en:"From", ta:"Irundhu", pron:"", cat:"Postposition"},
    {id:213, en:"Under", ta:"Keezhla", pron:"", cat:"Postposition"},
    {id:214, en:"Front", ta:"Munnadi", pron:"", cat:"Postposition"},
    {id:215, en:"Back", ta:"Pinnadi", pron:"", cat:"Postposition"},
    {id:216, en:"Liked (Past Tense)", ta:"Pudichithu", pron:"", cat:"Verb - Like"},
    {id:217, en:"Liked (Past Tense Question)", ta:"Pudichitha?", pron:"", cat:"Verb - Like"},
    {id:218, en:"I liking - Instant (Present Tense)", ta:"Pudichiruku", pron:"", cat:"Verb - Like"},
    {id:219, en:"I liking - Instant (Present Tense Question)", ta:"Pudichiruka?", pron:"", cat:"Verb - Like"},
    {id:220, en:"I like - Cont (Present Tense)", ta:"Pudikum", pron:"", cat:"Verb - Like"},
    {id:221, en:"I like - Cont (Present Tense Question)", ta:"Pudikuma?", pron:"", cat:"Verb - Like"},
    {id:222, en:"Understood (Past Tense)", ta:"Purinjuthu", pron:"", cat:"Verb - Understand"},
    {id:223, en:"Understood (Past Tense Question)", ta:"Purinjutha?", pron:"", cat:"Verb - Understand"},
    {id:224, en:"Understand (Present Tense - Instant)", ta:"Puriyuthu", pron:"", cat:"Verb - Understand"},
    {id:225, en:"Understand (Present Tense - Instant Question)", ta:"Puriyutha?", pron:"", cat:"Verb - Understand"},
    {id:226, en:"Understand (Present Tense - Cont)", ta:"Puriyum", pron:"", cat:"Verb - Understand"},
    {id:227, en:"Understand (Present Tense - Cont Question)", ta:"Puriyuma?", pron:"", cat:"Verb - Understand"},
    {id:228, en:"I knew [saw] (Past Tense)", ta:"Therinjuthu", pron:"", cat:"Verb - Know"},
    {id:229, en:"I knew [saw] (Past Tense Question)", ta:"Therinjutha?", pron:"", cat:"Verb - Know"},
    {id:230, en:"Know (Present Tense - Instant)", ta:"Theriyuthu", pron:"", cat:"Verb - Know"},
    {id:231, en:"Know (Present Tense - Instant Question)", ta:"Theriyutha?", pron:"", cat:"Verb - Know"},
    {id:232, en:"Know (Present Tense - Cont)", ta:"Theriyum", pron:"", cat:"Verb - Know"},
    {id:233, en:"Know (Present Tense - Cont Question)", ta:"Theriyuma?", pron:"", cat:"Verb - Know"},
    {id:234, en:"Day before yesterday", ta:"Mundha Nethu", pron:"", cat:"Time"},
    {id:235, en:"Day after tomorrow", ta:"Naalanaiku", pron:"", cat:"Time"},
    {id:236, en:"Day", ta:"Naal", pron:"", cat:"Time"},
    {id:237, en:"Week", ta:"Vaaram", pron:"", cat:"Time"},
    {id:238, en:"Month", ta:"Maasam", pron:"", cat:"Time"},
    {id:239, en:"Year", ta:"Varusham", pron:"", cat:"Time"},
    {id:240, en:"Second", ta:"Nodi", pron:"", cat:"Time"},
    {id:241, en:"Minute", ta:"Nimisham", pron:"", cat:"Time"},
    {id:242, en:"Hour", ta:"Mani Neram", pron:"", cat:"Time"},
    {id:243, en:"Clock", ta:"Mani", pron:"", cat:"Time"},
    {id:244, en:"2 weeks before", ta:"2 weeks Munnadi", pron:"", cat:"Time"},
    {id:245, en:"2 months after", ta:"2 weeks apram", pron:"", cat:"Time"},
    {id:246, en:"Last week", ta:"Ponna Varam", pron:"", cat:"Time"},
    {id:247, en:"This week", ta:"Indha Varam", pron:"", cat:"Time"},
    {id:248, en:"Next week", ta:"Adutha Varam", pron:"", cat:"Time"},
    {id:249, en:"Indian Money", ta:"Rupees", pron:"", cat:"Noun"},
    {id:250, en:"1", ta:"Onnu", pron:"", cat:"Number"},
    {id:251, en:"2", ta:"Rendu", pron:"", cat:"Number"},
    {id:252, en:"3", ta:"Moonu", pron:"", cat:"Number"},
    {id:253, en:"4", ta:"Naalu", pron:"", cat:"Number"},
    {id:254, en:"5", ta:"Aanchu", pron:"", cat:"Number"},
    {id:255, en:"6", ta:"Aaru", pron:"", cat:"Number"},
    {id:256, en:"7", ta:"Yellu", pron:"", cat:"Number"},
    {id:257, en:"8", ta:"Yettu", pron:"", cat:"Number"},
    {id:258, en:"9", ta:"Onbathu", pron:"", cat:"Number"},
    {id:259, en:"10", ta:"Pathu", pron:"", cat:"Number"},
    {id:260, en:"11", ta:"Pathionnu", pron:"", cat:"Number"},
    {id:261, en:"12", ta:"Panandu", pron:"", cat:"Number"}
];

// Opposite pairs for matching game
// Auto-detected and confirmed - 15 pairs total
const oppositePairs = [
    [1, 4],     // Morning - Night
    [111, 112], // Up - Down
    [113, 114], // Front - Back
    [115, 116], // Small - Big
    [117, 118], // Less - More
    [120, 121], // This - That
    [122, 123], // Here - There
    [124, 125], // Now - Then
    [128, 129], // Truth - Lie
    [130, 131], // Right - Wrong
    [132, 133], // Bitter - Sweet
    [138, 139], // Inside - Outside
    [140, 141], // Old - New
    [142, 144], // Yesterday - Tomorrow
    [148, 149]  // Yes - No
];

// Sentence templates for fill-in-the-blank exercises
// Use {word} as placeholder for the word to fill in
const sentenceTemplates = [
    // Time sentences
    {tamil: "{word} sapten", english: "I ate in the {word}", categories: ["Time"]},
    {tamil: "{word} vanakkam", english: "Good {word}", categories: ["Time"]},
    {tamil: "Naan {word} velai seiren", english: "I work in the {word}", categories: ["Time"]},
    {tamil: "{word} saapadu venum", english: "I want {word} food", categories: ["Time", "Time/Food"]},
    
    // Family sentences
    {tamil: "En {word} veetla irukanga", english: "My {word} is at home", categories: ["Family", "Family-Extended"]},
    {tamil: "Naan en {word}-oda pesuren", english: "I am talking with my {word}", categories: ["Family", "Family-Extended"]},
    {tamil: "{word} irukanga", english: "{word} is here", categories: ["Family", "Family-Extended", "Family-Question"]},
    
    // Question words
    {tamil: "{word} pesura?", english: "{word} is speaking?", categories: ["Question Word"]},
    {tamil: "{word} poganum?", english: "{word} should I go?", categories: ["Question Word"]},
    {tamil: "{word} vandha?", english: "{word} did you come?", categories: ["Question Word"]},
    {tamil: "{word} irukeenga?", english: "{word} are you?", categories: ["Question Word"]},
    
    // Pronouns
    {tamil: "{word} saapten", english: "{word} ate", categories: ["Pronoun"]},
    {tamil: "{word} inga irukkom", english: "{word} are here", categories: ["Pronoun"]},
    {tamil: "{word} poganum", english: "{word} should go", categories: ["Pronoun"]},
    
    // Verb Conjugations
    {tamil: "{word}", english: "{word}", categories: ["Verb Conjugation", "Question Conjugation"]},
    {tamil: "Naan {word}", english: "I {word}", categories: ["Verb Conjugation"]},
    
    // Possessives
    {tamil: "{word} veedu", english: "{word} house", categories: ["Possessive"]},
    {tamil: "{word} paiyan", english: "{word} boy", categories: ["Possessive"]},
    
    // Location/Direction
    {tamil: "{word} podu", english: "Put it {word}", categories: ["Location/Adverb", "Postposition", "Location"]},
    {tamil: "{word} paaru", english: "Look {word}", categories: ["Location/Adverb"]},
    {tamil: "Naan {word} irukken", english: "I am {word}", categories: ["Location", "Location/Adverb"]},
    
    // Adjectives
    {tamil: "Idhu romba {word}", english: "This is very {word}", categories: ["Adjective"]},
    {tamil: "{word} veedu", english: "{word} house", categories: ["Adjective"]},
    {tamil: "{word} saapadu", english: "{word} food", categories: ["Adjective", "Taste"]},
    
    // Quantity
    {tamil: "Enaku {word} venum", english: "I want {word}", categories: ["Quantity"]},
    {tamil: "{word} iruku", english: "There is {word}", categories: ["Quantity"]},
    
    // Demonstrative
    {tamil: "{word} veedu periya", english: "{word} house is big", categories: ["Demonstrative"]},
    {tamil: "{word} en veedu", english: "{word} is my house", categories: ["Demonstrative"]},
    
    // Taste
    {tamil: "Idhu {word}", english: "This is {word}", categories: ["Taste"]},
    {tamil: "{word} saapadu venum", english: "I want {word} food", categories: ["Taste"]},
    
    // Verbs
    {tamil: "Enaku {word}", english: "I {word}", categories: ["Verb", "Verb - Present Cont.", "Verb - Like", "Verb - Understand", "Verb - Know"]},
    {tamil: "Ungaluku {word}?", english: "Do you {word}?", categories: ["Verb", "Verb - Present Cont."]},
    {tamil: "Naan {word}", english: "I {word}", categories: ["Verb - Past Negative"]},
    
    // Numbers
    {tamil: "Enaku {word} venum", english: "I want {word}", categories: ["Number"]},
    {tamil: "{word} per irukanga", english: "There are {word} people", categories: ["Number"]},
    {tamil: "{word} veedu", english: "{word} houses", categories: ["Number"]},
    
    // Conjunctions
    {tamil: "{word}, naan pogiren", english: "{word}, I am going", categories: ["Affirmation/Negation", "Conjunction"]},
    {tamil: "Naan vandhan, {word} avaru vandhrau", english: "I came, {word} he came", categories: ["Conjunction", "Conjunction/Time"]},
    
    // Postpositions
    {tamil: "Veedu {word} iruku", english: "The house is {word}", categories: ["Postposition"]},
    {tamil: "Naan {word} pogiren", english: "I am going {word}", categories: ["Postposition"]},
    
    // Dative pronouns
    {tamil: "{word} pudikum", english: "I/You like (to {word})", categories: ["Personal Pronoun-Dative"]},
    {tamil: "{word} theriyum", english: "I/You know (to {word})", categories: ["Personal Pronoun-Dative"]},
    
    // Non-personal pronouns
    {tamil: "{word} pesuren", english: "I'm talking {word}", categories: ["Non Personal Pronoun"]},
    {tamil: "{word} vandhen", english: "I came {word}", categories: ["Non Personal Pronoun"]},
    
    // General templates that work with most words
    {tamil: "Idhu {word}", english: "This is {word}", categories: ["Time", "Family", "Noun", "Adjective", "Taste", "People", "Demonstrative", "Manner", "Abstract"]},
    {tamil: "Adhu {word} illa", english: "That is not {word}", categories: ["Adjective", "Noun", "Demonstrative"]},
    {tamil: "{word}?", english: "{word}?", categories: ["Question Word", "Question Conjugation", "Family-Question"]}
];
