// Tamil Master Vocabulary Database
// Last updated: 2026-04-13
// Total words: 421
// Verb data cleaned and enhanced with grammar metadata:
//   - 70 verb conjugations with full grammar structure
//   - 3 verb types: regular, dative-stative, modal-auxiliary-dative-stative
//   - Grammar fields: verbType, tense, aspect, polarity, form, person
//   - Research-based categorization (see VERB_CLEANUP.md)

const data = [
    {id:1, en:"Morning", ta:"Kaalai", pron:"Kaa-lai", cat:"Time"},
    {id:2, en:"Afternoon", ta:"Madhiyam", pron:"Ma-dhe-ya-im", cat:"Time"},
    {id:3, en:"Evening", ta:"Maalai", pron:"Maa-lai Saaingalam", cat:"Time"},
    {id:4, en:"Night", ta:"Rathiri", pron:"Raath-ree", cat:"Time"},
    {id:5, en:"Good Morning", ta:"Kaalai Vanakkam", pron:"", cat:"Time"},
    {id:6, en:"Good Afternoon", ta:"Madhiyam Vanakkam", pron:"", cat:"Time"},
    {id:7, en:"Good Evening", ta:"Maalai Vanakkam", pron:"", cat:"Time"},
    {id:8, en:"Good night", ta:"Rathiri Vanakkam", pron:"", cat:"Time"},
    {id:9, en:"Breakfast", ta:"Kaalai Saapadu", pron:"food", cat:"Time/Food"},
    {id:10, en:"Lunch", ta:"Madhiyam Sapadu", pron:"", cat:"Time/Food"},
    {id:11, en:"Dinner", ta:"Rathiri Sapadu", pron:"", cat:"Time/Food"},
    {id:12, en:"Father", ta:"Appa", pron:"Aa-ip-paa", cat:"Family"},
    {id:13, en:"Mother", ta:"Amma", pron:"Aa-im-maa", cat:"Family"},
    {id:14, en:"Grandfather", ta:"Thatha", pron:"Thaa-ith-tha", cat:"Family"},
    {id:15, en:"Grandmother", ta:"Paati", pron:"Paa-it-tea", cat:"Family"},
    {id:16, en:"Older brother", ta:"Anna", pron:"Aa-in-naa", cat:"Family"},
    {id:17, en:"Older sister", ta:"Akka", pron:"Aa-ik-kaa", cat:"Family"},
    {id:18, en:"Younger brother", ta:"Thumbi", pron:"Thumb--bee", cat:"Family"},
    {id:19, en:"Younger sister", ta:"Thangachi", pron:"Thaa-nga-ga-chee", cat:"Family"},
    {id:20, en:"Uncle", ta:"Mama", pron:"Maa-im-ma", cat:"Family"},
    {id:21, en:"Aunty", ta:"Maami / Athai", pron:"Maa-mee / aa-ith-ai", cat:"Family"},
    {id:22, en:"Husband", ta:"Kanavan", pron:"Ka-na-va-in / Purushan", cat:"Family"},
    {id:23, en:"Wife", ta:"Manaivi", pron:"Maa-nai-vee / Pondatii", cat:"Family"},
    {id:24, en:"Father's older brother - Big Dad", ta:"Periyaappa", pron:"PeriyaAmma", cat:"Family-Extended"},
    {id:25, en:"Father's younger brother - Small Dad", ta:"Chithappa (ChinnaAppa)", pron:"Chithappa / ChinnaAppa", cat:"Family-Extended"},
    {id:26, en:"Father's younger sister - Small Aunty", ta:"Chinnaathai", pron:"ChinnaMama", cat:"Family-Extended"},
    {id:27, en:"Father's older sister - Big Aunty", ta:"Periyaathai", pron:"PeriyaMama", cat:"Family-Extended"},
    {id:28, en:"Mother's older brother - Big Uncle", ta:"PeriyaMama", pron:"PeriyaAthai", cat:"Family-Extended"},
    {id:29, en:"Mother's younger brother - Small Uncle", ta:"ChinnaMama", pron:"ChinnaAthai", cat:"Family-Extended"},
    {id:30, en:"Mother's younger sister - Small Mom", ta:"ChinnaAmma (Chithi)", pron:"ChinnaAmma / Chithi", cat:"Family-Extended"},
    {id:31, en:"Mother's older sister - Big Mom", ta:"PeriyaAmma", pron:"PeriyaAppa", cat:"Family-Extended"},
    {id:32, en:"What", ta:"Yenna", pron:"Ye-in-na", cat:"Question Word"},
    {id:33, en:"When", ta:"Yeppo", pron:"Yup-po", cat:"Question Word"},
    {id:34, en:"Where", ta:"Yenga", pron:"Ye-ing-ga", cat:"Question Word"},
    {id:35, en:"Who", ta:"Yaaru", pron:"Yaa-roo", cat:"Question Word"},
    {id:36, en:"Why", ta:"Yaen", pron:"Yae-in", cat:"Question Word"},
    {id:37, en:"How", ta:"Eppadi", pron:"Yup-pa-di", cat:"Question Word"},
    {id:38, en:"How many", ta:"Yethana", pron:"Ye-ith-tha-na", cat:"Question Word"},
    {id:39, en:"How much", ta:"Yevlo", pron:"Ye-iv-lo", cat:"Question Word"},
    {id:40, en:"From where", ta:"Yenga Irundhu", pron:"Ye-ing-ga Ee-ru-indh-uu", cat:"Question Word"},
    {id:41, en:"For what", ta:"Yethuku/Yethukaga", pron:"Ye-thu-ku / Ye-thu-ka-ga", cat:"Question Word"},
    {id:42, en:"Which", ta:"Yethu", pron:"Ye-thu", cat:"Question Word"},
    {id:43, en:"Whose", ta:"Yaarodathu", pron:"Yaa-ro-da-thu", cat:"Question Word"},
    {id:44, en:"I", ta:"Naan", pron:"Naa-in", cat:"Pronoun"},
    {id:45, en:"You", ta:"Neenga", pron:"Nee-ing-ga", cat:"Pronoun"},
    {id:46, en:"He", ta:"Avaru", pron:"Aa-va-ru", cat:"Pronoun"},
    {id:47, en:"She/They", ta:"Avanga", pron:"Aa-vang-ga", cat:"Pronoun"},
    {id:48, en:"We - Including Listener", ta:"Namma", pron:"Na-im-ma", cat:"Pronoun"},
    {id:49, en:"We - Excluding Listener", ta:"Naanga", pron:"Naa-ing-ga", cat:"Pronoun"},
    {id:50, en:"I was", enClean:"I was", ta:"Irundhan", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"I"}, relatedWords:[51,52,79,85,91]},
    {id:51, en:"I am", enClean:"I am", ta:"Irukan", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"I"}, relatedWords:[50,52,79,85,91]},
    {id:52, en:"I will be", enClean:"I will be", ta:"Irupan", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"I"}, relatedWords:[50,51,79,85,91]},
    {id:53, en:"You were", enClean:"You were", ta:"Irundheenga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"you"}, relatedWords:[54,55,80,86,92]},
    {id:54, en:"You are", enClean:"You are", ta:"Irukeenga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"you"}, relatedWords:[53,55,80,86,92]},
    {id:55, en:"You will be", enClean:"You will be", ta:"Irupeenga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"you"}, relatedWords:[53,54,80,86,92]},
    {id:56, en:"He was", enClean:"He was", ta:"Irundharu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"he"}, relatedWords:[57,58,81,87,93]},
    {id:57, en:"He is", enClean:"He is", ta:"Irukaru", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"he"}, relatedWords:[56,58,81,87,93]},
    {id:58, en:"He will be", enClean:"He will be", ta:"Iruparu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"he"}, relatedWords:[56,57,81,87,93]},
    {id:59, en:"She/They were", enClean:"She/They were", ta:"Irundhanga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"they"}, relatedWords:[60,61,82,88,94]},
    {id:60, en:"She/They are", enClean:"She/They are", ta:"Irukanga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"they"}, relatedWords:[59,61,82,88,94]},
    {id:61, en:"She/They will be", enClean:"She/They will be", ta:"Irupanga", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"they"}, relatedWords:[59,60,82,88,94]},
    {id:62, en:"We were (Inc.)", enClean:"We were", ta:"Irundhom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"we-inc"}, relatedWords:[63,64,83,89,95]},
    {id:63, en:"We are (Inc.)", enClean:"We are", ta:"Irukom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"we-inc"}, relatedWords:[62,64,83,89,95]},
    {id:64, en:"We will be (Inc.)", enClean:"We will be", ta:"Irupom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"we-inc"}, relatedWords:[62,63,83,89,95]},
    {id:65, en:"We were (Exc.)", enClean:"We were", ta:"Irundhom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"we-exc"}, relatedWords:[66,67]},
    {id:66, en:"We are (Exc.)", enClean:"We are", ta:"Irukom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"we-exc"}, relatedWords:[65,67]},
    {id:67, en:"We will be (Exc.)", enClean:"We will be", ta:"Irupom", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"we-exc"}, relatedWords:[65,66]},
    {id:68, en:"It was", enClean:"It was", ta:"Irundhuchu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"statement", person:"non-human"}, relatedWords:[69,70,84,90,96]},
    {id:69, en:"It is", enClean:"It is", ta:"Iruku", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"statement", person:"non-human"}, relatedWords:[68,70,84,90,96]},
    {id:70, en:"It will be", enClean:"It will be", ta:"Irukum", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"statement", person:"non-human"}, relatedWords:[68,69,84,90,96]},
    {id:71, en:"My", ta:"Ennoda / En", pron:"", cat:"Possessive"},
    {id:72, en:"Your", ta:"Ungaloda / Unga", pron:"", cat:"Possessive"},
    {id:73, en:"His", ta:"Avaroda", pron:"", cat:"Possessive"},
    {id:74, en:"Her/Their", ta:"Avangaloda", pron:"", cat:"Possessive"},
    {id:75, en:"Our", ta:"Nammaloda", pron:"", cat:"Possessive"},
    {id:76, en:"Us (Our - Exc.)", ta:"Engaloda", pron:"", cat:"Possessive"},
    {id:79, en:"Was I?", enClean:"Was I?", ta:"Irundhana?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"I"}, relatedWords:[50,51,52,85,91]},
    {id:80, en:"Were you?", enClean:"Were you?", ta:"Irundheengala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"you"}, relatedWords:[53,54,55,86,92]},
    {id:81, en:"Was he?", enClean:"Was he?", ta:"Irundhara?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"he"}, relatedWords:[56,57,58,87,93]},
    {id:82, en:"Were she/they?", enClean:"Were she/they?", ta:"Irundhangala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"they"}, relatedWords:[59,60,61,88,94]},
    {id:83, en:"Were we?", enClean:"Were we?", ta:"Irundhoma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"we"}, relatedWords:[62,63,64,65,66,67,89,95]},
    {id:84, en:"Was it?", enClean:"Was it?", ta:"Irundhucha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"past", aspect:null, polarity:"positive", form:"question", person:"non-human"}, relatedWords:[68,69,70,90,96]},
    {id:85, en:"Am I?", enClean:"Am I?", ta:"Irukana?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"I"}, relatedWords:[50,51,52,79,91]},
    {id:86, en:"Are you?", enClean:"Are you?", ta:"Irukeengala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"you"}, relatedWords:[53,54,55,80,92]},
    {id:87, en:"Is he?", enClean:"Is he?", ta:"Irukara?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"he"}, relatedWords:[56,57,58,81,93]},
    {id:88, en:"Are she/they?", enClean:"Are she/they?", ta:"Irukangala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"they"}, relatedWords:[59,60,61,82,94]},
    {id:89, en:"Are we?", enClean:"Are we?", ta:"Irukoma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"we"}, relatedWords:[62,63,64,65,66,67,83,95]},
    {id:90, en:"Is it?", enClean:"Is it?", ta:"Iruka?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"present", aspect:"continuous", polarity:"positive", form:"question", person:"non-human"}, relatedWords:[68,69,70,84,96]},
    {id:91, en:"Will I be?", enClean:"Will I be?", ta:"Irupana?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"I"}, relatedWords:[50,51,52,79,85]},
    {id:92, en:"Will you be?", enClean:"Will you be?", ta:"Irupeengala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"you"}, relatedWords:[53,54,55,80,86]},
    {id:93, en:"Will he be?", enClean:"Will he be?", ta:"Irupara?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"he"}, relatedWords:[56,57,58,81,87]},
    {id:94, en:"Will she/they be?", enClean:"Will she/they be?", ta:"Irupangala?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"they"}, relatedWords:[59,60,61,82,88]},
    {id:95, en:"Will we be?", enClean:"Will we be?", ta:"Irupoma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"we"}, relatedWords:[62,63,64,65,66,67,83,89]},
    {id:96, en:"Will it be?", enClean:"Will it be?", ta:"Irukuma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Irukka", verbType:"regular", tense:"future", aspect:null, polarity:"positive", form:"question", person:"non-human"}, relatedWords:[68,69,70,84,90]},
    {id:97, en:"Father (/?)", ta:"Appa-va?", pron:"", cat:"Family-Question"},
    {id:98, en:"Mother (/?)", ta:"Amma-va?", pron:"", cat:"Family-Question"},
    {id:99, en:"Grandfather (/?)", ta:"Thatha-va?", pron:"", cat:"Family-Question"},
    {id:100, en:"Grandmother (/?)", ta:"Paati-ya?", pron:"", cat:"Family-Question"},
    {id:101, en:"Older brother (/?)", ta:"Anna-va?", pron:"", cat:"Family-Question"},
    {id:102, en:"Older sister (/?)", ta:"Akka-va?", pron:"", cat:"Family-Question"},
    {id:103, en:"Younger brother (/?)", ta:"Thumbi-ya?", pron:"", cat:"Family-Question"},
    {id:104, en:"Younger sister (/?)", ta:"Thungachi-ya?", pron:"", cat:"Family-Question"},
    {id:105, en:"Uncle (/?)", ta:"Mama-va?", pron:"", cat:"Family-Question"},
    {id:106, en:"Aunty (/?)", ta:"Maami-ya? Athai-ya?", pron:"", cat:"Family-Question"},
    {id:107, en:"Husband (/?)", ta:"Kanava-ah? Purushana?", pron:"", cat:"Family-Question"},
    {id:108, en:"Wife (/?)", ta:"Manaivi-ya? Pondatii-ya?", pron:"", cat:"Family-Question"},
    {id:109, en:"Boy/Son", ta:"Paiyan", pron:"Paa-ai-ya-in", cat:"People"},
    {id:110, en:"Girl/Daughter", ta:"Ponnu", pron:"Poo-in-nu", cat:"People"},
    {id:111, en:"Up/Above/On/Upstairs", ta:"Maela", pron:"MAY-le", cat:"Location/Adverb"},
    {id:112, en:"Below/Under/Down/Downstairs", ta:"Keela", pron:"KEY-le", cat:"Location/Adverb"},
    {id:113, en:"Front/Before/Infront", ta:"Munnadi", pron:"MU-naddi", cat:"Location/Adverb"},
    {id:114, en:"Back/After/Behind", ta:"Pinnadi", pron:"PI-naddi", cat:"Location/Adverb"},
    {id:115, en:"Small", ta:"Chinnathu/Chinna", pron:"CHIN-ath-e / Che-in-na", cat:"Adjective"},
    {id:116, en:"Big", ta:"Perusu/Periya", pron:"Pae-ree-ya / Pe-ru-su", cat:"Adjective"},
    {id:117, en:"Little/Less", ta:"Konjam / Kammi", pron:"Koo-in-jam / Kaa-im-me", cat:"Quantity"},
    {id:118, en:"More/Very/A lot", ta:"Neraiya/Romba", pron:"NE-ray-uh / RUUM-ba", cat:"Quantity"},
    {id:119, en:"Many", ta:"Adhigam", pron:"UH-di-gum", cat:"Quantity"},
    {id:120, en:"This", ta:"Idhu / Indha", pron:"", cat:"Demonstrative"},
    {id:121, en:"That", ta:"Adhu / Andha", pron:"", cat:"Demonstrative"},
    {id:122, en:"Here", ta:"Inga", pron:"", cat:"Location"},
    {id:123, en:"There", ta:"Anga", pron:"", cat:"Location"},
    {id:124, en:"Now", ta:"Ippo", pron:"", cat:"Time"},
    {id:125, en:"Then/while/during", ta:"Appo", pron:"", cat:"Time"},
    {id:126, en:"Like this", ta:"Indha Mathiri / Ippadi", pron:"", cat:"Manner"},
    {id:127, en:"Like that", ta:"Andha Mathiri / Appadi", pron:"", cat:"Manner"},
    {id:128, en:"Truth", ta:"Unmai", pron:"", cat:"Abstract"},
    {id:129, en:"Lie", ta:"Poi", pron:"", cat:"Abstract"},
    {id:130, en:"Correct/Right/Okay", ta:"Sari", pron:"Cherry", cat:"Abstract"},
    {id:131, en:"Wrong/mistake", ta:"Thappu", pron:"", cat:"Abstract"},
    {id:132, en:"Bitter", ta:"Kasapu", pron:"", cat:"Taste"},
    {id:133, en:"Sweet", ta:"Inipu", pron:"", cat:"Taste"},
    {id:134, en:"Sour", ta:"Pulipu", pron:"", cat:"Taste"},
    {id:135, en:"Salt", ta:"Uppu", pron:"", cat:"Taste"},
    {id:136, en:"Tart", ta:"Thuvarpu", pron:"", cat:"Taste"},
    {id:137, en:"Spicy", ta:"Kaaram", pron:"", cat:"Taste"},
    {id:138, en:"Inside", ta:"Ulla", pron:"", cat:"Location"},
    {id:139, en:"Outside", ta:"Veliya", pron:"", cat:"Location"},
    {id:140, en:"Old", ta:"Palaya/Palasu", pron:"", cat:"Adjective"},
    {id:141, en:"New", ta:"Pudhu/Pudhusu", pron:"", cat:"Adjective"},
    {id:142, en:"Yesterday", ta:"Nethu", pron:"", cat:"Time"},
    {id:143, en:"Today", ta:"Inaiku", pron:"", cat:"Time"},
    {id:144, en:"Tomorrow", ta:"Naalaiku", pron:"", cat:"Time"},
    {id:145, en:"House", ta:"Veedu", pron:"", cat:"Noun"},
    {id:146, en:"In the House", ta:"Veetla", pron:"", cat:"Noun"},
    {id:147, en:"To the House", ta:"Veetuku", pron:"", cat:"Noun"},
    {id:148, en:"Yes", ta:"Aama", pron:"", cat:"Affirmation/Negation"},
    {id:149, en:"No/Not/Not there/Neither/Either/Or", ta:"illa", pron:"", cat:"Affirmation/Negation"},
    {id:150, en:"But", ta:"Aana", pron:"", cat:"Conjunction"},
    {id:151, en:"Because", ta:"Yaena", pron:"", cat:"Conjunction"},
    {id:152, en:"And/After", ta:"Apram", pron:"", cat:"Conjunction/Time"},
    {id:153, en:"Name/People", ta:"Peru", pron:"", cat:"Noun"},
    {id:154, en:"To me", ta:"Enaku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:155, en:"To you", ta:"Ungaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:156, en:"To him", ta:"Avaruku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:157, en:"To her/them", ta:"Avangaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:158, en:"To us (Inc.)", ta:"Nammaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:159, en:"To us (Exc.)", ta:"Engaluku", pron:"", cat:"Personal Pronoun-Dative"},
    {id:162, en:"To me", ta:"Enkitta", pron:"", cat:"Non Personal Pronoun"},
    {id:163, en:"To you", ta:"Ungakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:164, en:"To him", ta:"Avarukitta", pron:"", cat:"Non Personal Pronoun"},
    {id:165, en:"To her/them", ta:"Avangakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:166, en:"To us (Inc.)", ta:"Nammakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:167, en:"To us (Exc.)", ta:"Engakitta", pron:"", cat:"Non Personal Pronoun"},
    {id:173, en:"Don't you like?", enClean:"Don't you like?", ta:"Pudikatha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[216,217,194,197,218,219,220,221]},
    {id:174, en:"Want/Need", enClean:"Want", ta:"Venum", pron:"Ve-nu-im", cat:"Verb", type:"conjugation", grammar:{base:"Venum", verbType:"modal-auxiliary-dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[175,176,177]},
    {id:175, en:"Don't want/need", enClean:"Don't want", ta:"Vendam", pron:"Ve-in-da-im", cat:"Verb", type:"conjugation", grammar:{base:"Venum", verbType:"modal-auxiliary-dative-stative", tense:"present-habitual", aspect:null, polarity:"negative", form:"statement", person:null}, relatedWords:[174,176,177]},
    {id:176, en:"Do you want?", enClean:"Do you want?", ta:"Venuma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Venum", verbType:"modal-auxiliary-dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[174,175,177]},
    {id:177, en:"Don't you want?", enClean:"Don't you want?", ta:"Vendama?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Venum", verbType:"modal-auxiliary-dative-stative", tense:"present-habitual", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[174,175,176]},
    {id:181, en:"Don't you understand?", enClean:"Don't you understand?", ta:"Puriyatha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[222,223,196,199,224,225,226,227]},
    {id:185, en:"Don't you know?", enClean:"Don't you know?", ta:"Theriyatha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[228,229,195,198,230,231,232,233]},
    {id:186, en:"Enough (Quantity)", ta:"Podhum", pron:"Po-dhu-im", cat:"Quantity"},
    {id:187, en:"Enough (Measurement)", ta:"Pathum", pron:"Pa-ith-um", cat:"Quantity"},
    {id:188, en:"Enough (Quantity -)", ta:"Podhathu", pron:"Po-dha-thu", cat:"Quantity"},
    {id:189, en:"Enough (Measurement -)", ta:"Pathathu", pron:"Pa-ith-tha-thu", cat:"Quantity"},
    {id:190, en:"Enough (Quantity /?)", ta:"Podhuma?", pron:"", cat:"Quantity"},
    {id:191, en:"Enough (Measurement /?)", ta:"Pathuma?", pron:"", cat:"Quantity"},
    {id:192, en:"Enough (Quantity - /?)", ta:"Podhatha?", pron:"", cat:"Quantity"},
    {id:193, en:"Enough (Measurement - /?)", ta:"Pathatha?", pron:"", cat:"Quantity"},
    {id:194, en:"Didn't like", enClean:"Didn't like", ta:"Pudikala", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"statement", person:null}, relatedWords:[216,217,197,218,219,220,221,173]},
    {id:195, en:"Didn't know", enClean:"Didn't know", ta:"Therila", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"statement", person:null}, relatedWords:[228,229,198,230,231,232,233,185]},
    {id:196, en:"Didn't understand", enClean:"Didn't understand", ta:"Purila", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"statement", person:null}, relatedWords:[222,223,199,224,225,226,227,181]},
    {id:197, en:"Didn't you like?", enClean:"Didn't you like?", ta:"Pudikalaiya?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[216,217,194,218,219,220,221,173]},
    {id:198, en:"Didn't you know?", enClean:"Didn't you know?", ta:"Therilaiya?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[228,229,195,230,231,232,233,185]},
    {id:199, en:"Didn't you understand?", enClean:"Didn't you understand?", ta:"Purilaiya?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"negative", form:"question", person:null}, relatedWords:[222,223,196,224,225,226,227,181]},
    {id:200, en:"In/at", ta:"la", pron:"", cat:"Postposition"},
    {id:201, en:"With", ta:"Kuda", pron:"", cat:"Postposition"},
    {id:202, en:"Without", ta:"illama", pron:"", cat:"Postposition"},
    {id:203, en:"For", ta:"Kaga", pron:"", cat:"Postposition"},
    {id:204, en:"About", ta:"Pathi", pron:"", cat:"Postposition"},
    {id:205, en:"Because of", ta:"Naela", pron:"", cat:"Postposition"},
    {id:206, en:"Inside", ta:"Ulla", pron:"", cat:"Postposition"},
    {id:207, en:"Outside", ta:"Veliya", pron:"", cat:"Postposition"},
    {id:208, en:"To - Inside", ta:"Ku", pron:"", cat:"Postposition"},
    {id:209, en:"To - Nearby", ta:"Kitta", pron:"", cat:"Postposition"},
    {id:210, en:"On", ta:"Maela", pron:"", cat:"Postposition"},
    {id:211, en:"If", ta:"na", pron:"", cat:"Conjunction"},
    {id:212, en:"From", ta:"Irundhu", pron:"", cat:"Postposition"},
    {id:213, en:"Under", ta:"Keezhla", pron:"", cat:"Postposition"},
    {id:214, en:"Front", ta:"Munnadi", pron:"", cat:"Postposition"},
    {id:215, en:"Back", ta:"Pinnadi", pron:"", cat:"Postposition"},
    {id:216, en:"Liked", enClean:"Liked", ta:"Pudichithu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[217,194,197,218,219,220,221,173]},
    {id:217, en:"Did you like?", enClean:"Did you like?", ta:"Pudichitha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[216,194,197,218,219,220,221,173]},
    {id:218, en:"Liking (now)", enClean:"Liking", ta:"Pudichiruku", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[216,217,194,197,219,220,221,173]},
    {id:219, en:"Are you liking (now)?", enClean:"Are you liking?", ta:"Pudichiruka?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[216,217,194,197,218,220,221,173]},
    {id:220, en:"Like (general)", enClean:"Like", ta:"Pudikum", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[216,217,194,197,218,219,221,173]},
    {id:221, en:"Do you like?", enClean:"Do you like?", ta:"Pudikuma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Pudikka", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[216,217,194,197,218,219,220,173]},
    {id:222, en:"Understood", enClean:"Understood", ta:"Purinjuthu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[223,196,199,224,225,226,227,181]},
    {id:223, en:"Did you understand?", enClean:"Did you understand?", ta:"Purinjutha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[222,196,199,224,225,226,227,181]},
    {id:224, en:"Understand (now)", enClean:"Understand", ta:"Puriyuthu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[222,223,196,199,225,226,227,181]},
    {id:225, en:"Do you understand (now)?", enClean:"Do you understand?", ta:"Puriyutha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[222,223,196,199,224,226,227,181]},
    {id:226, en:"Understand (general)", enClean:"Understand", ta:"Puriyum", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[222,223,196,199,224,225,227,181]},
    {id:227, en:"Do you understand?", enClean:"Do you understand?", ta:"Puriyuma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Puriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[222,223,196,199,224,225,226,181]},
    {id:228, en:"Knew/Found out", enClean:"Knew", ta:"Therinjuthu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[229,195,198,230,231,232,233,185]},
    {id:229, en:"Did you know?", enClean:"Did you know?", ta:"Therinjutha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"past", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[228,195,198,230,231,232,233,185]},
    {id:230, en:"Know (realizing now)", enClean:"Know", ta:"Theriyuthu", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[228,229,195,198,231,232,233,185]},
    {id:231, en:"Do you know (now)?", enClean:"Do you know?", ta:"Theriyutha?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"present-momentary", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[228,229,195,198,230,232,233,185]},
    {id:232, en:"Know (general)", enClean:"Know", ta:"Theriyum", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"statement", person:null}, relatedWords:[228,229,195,198,230,231,233,185]},
    {id:233, en:"Do you know?", enClean:"Do you know?", ta:"Theriyuma?", pron:"", cat:"Verb", type:"conjugation", grammar:{base:"Theriya", verbType:"dative-stative", tense:"present-habitual", aspect:null, polarity:"positive", form:"question", person:null}, relatedWords:[228,229,195,198,230,231,232,185]},
    {id:234, en:"Day before yesterday", ta:"Mundha Nethu", pron:"", cat:"Time"},
    {id:235, en:"Day after tomorrow", ta:"Naalanaiku", pron:"", cat:"Time"},
    {id:236, en:"Day", ta:"Naal", pron:"", cat:"Time"},
    {id:237, en:"Week", ta:"Vaaram", pron:"", cat:"Time"},
    {id:238, en:"Month", ta:"Maasam", pron:"", cat:"Time"},
    {id:239, en:"Year", ta:"Varusham", pron:"", cat:"Time"},
    {id:240, en:"Second", ta:"Nodi", pron:"", cat:"Time"},
    {id:241, en:"Minute", ta:"Nimisham", pron:"", cat:"Time"},
    {id:242, en:"Hour", ta:"Mani Neram", pron:"", cat:"Time"},
    {id:243, en:"Clock", ta:"Mani", pron:"", cat:"Time"},
    {id:244, en:"2 weeks before", ta:"2 weeks Munnadi", pron:"", cat:"Time"},
    {id:245, en:"2 months after", ta:"2 weeks apram", pron:"", cat:"Time"},
    {id:246, en:"Last week", ta:"Ponna Varam", pron:"", cat:"Time"},
    {id:247, en:"This week", ta:"Indha Varam", pron:"", cat:"Time"},
    {id:248, en:"Next week", ta:"Adutha Varam", pron:"", cat:"Time"},
    {id:249, en:"Indian Money", ta:"Rupees", pron:"", cat:"Noun"},
    {id:250, en:"1", ta:"Onnu", pron:"", cat:"Number"},
    {id:251, en:"2", ta:"Rendu", pron:"", cat:"Number"},
    {id:252, en:"3", ta:"Moonu", pron:"", cat:"Number"},
    {id:253, en:"4", ta:"Naalu", pron:"", cat:"Number"},
    {id:254, en:"5", ta:"Aanchu", pron:"", cat:"Number"},
    {id:255, en:"6", ta:"Aaru", pron:"", cat:"Number"},
    {id:256, en:"7", ta:"Yellu", pron:"", cat:"Number"},
    {id:257, en:"8", ta:"Yettu", pron:"", cat:"Number"},
    {id:258, en:"9", ta:"Onbathu", pron:"", cat:"Number"},
    {id:259, en:"10", ta:"Pathu", pron:"", cat:"Number"},
    {id:260, en:"11", ta:"Pathinonnu", pron:"", cat:"Number"},
    {id:261, en:"12", ta:"Panandu", pron:"", cat:"Number"},

    // Greetings
    {id:262, en:"Hello / Hi / Bye", ta:"Vanakkam", pron:"Vaa-naa-kaa-im", cat:"Greeting"},
    {id:263, en:"Thank you", ta:"Nandree", pron:"Nun-dree", cat:"Greeting"},
    {id:264, en:"Food / Meal", ta:"Sapadu", pron:"", cat:"Noun"},

    // Colors
    {id:265, en:"Green", ta:"Patchai", pron:"", cat:"Color"},
    {id:266, en:"Blue", ta:"Neelam", pron:"", cat:"Color"},
    {id:267, en:"Red", ta:"Sivapu", pron:"", cat:"Color"},
    {id:268, en:"Pink", ta:"Ilamsivapu", pron:"", cat:"Color"},
    {id:269, en:"Yellow", ta:"Manjal", pron:"", cat:"Color"},
    {id:270, en:"Orange", ta:"Semmanjal", pron:"", cat:"Color"},
    {id:271, en:"Black", ta:"Karupu", pron:"", cat:"Color"},
    {id:272, en:"White", ta:"Vellai", pron:"", cat:"Color"},
    {id:273, en:"Grey", ta:"Saambal Niram", pron:"", cat:"Color"},
    {id:274, en:"Violet", ta:"Ootha", pron:"", cat:"Color"},

    // Days of the Week (ta = full form, pron = short form)
    {id:275, en:"Sunday", ta:"Niyayatru Kilamai", pron:"Niyayaru", cat:"Day"},
    {id:276, en:"Monday", ta:"Thingal Kilamai", pron:"Thingal", cat:"Day"},
    {id:277, en:"Tuesday", ta:"Sevvai Kilamai", pron:"Sevvai", cat:"Day"},
    {id:278, en:"Wednesday", ta:"Bhudhan Kilamai", pron:"Bhudhan", cat:"Day"},
    {id:279, en:"Thursday", ta:"Viyalak Kilamai", pron:"Viyalan", cat:"Day"},
    {id:280, en:"Friday", ta:"Velli Kilamai", pron:"Velli", cat:"Day"},
    {id:281, en:"Saturday", ta:"Sani Kilamai", pron:"Sani", cat:"Day"},

    // Connectors and Particles
    {id:282, en:"Because of that", ta:"Athunaela", pron:"", cat:"Conjunction"},
    {id:283, en:"A / An", ta:"Oru", pron:"", cat:"Abstract"},
    {id:284, en:"Some", ta:"Sila", pron:"", cat:"Quantity"},
    {id:285, en:"Frequently / Now and then", ta:"Appo Appo", pron:"", cat:"Adverb"},
    {id:286, en:"Simply / Just like that", ta:"Chumma", pron:"", cat:"Adverb"},
    {id:287, en:"Different", ta:"Vera", pron:"", cat:"Adjective"},
    {id:288, en:"Than (comparisons)", ta:"Vida", pron:"", cat:"Postposition"},
    {id:289, en:"Work", ta:"Vaelai", pron:"", cat:"Noun"},
    {id:290, en:"Money", ta:"Panam", pron:"", cat:"Noun"},

    // Key Verbs (base forms)
    {id:291, en:"Do / Make", ta:"Pannu", pron:"", cat:"Verb", type:"base"},
    {id:292, en:"Tell / Say", ta:"Sollu", pron:"", cat:"Verb", type:"base"},
    {id:293, en:"Eat", ta:"Sapudu", pron:"", cat:"Verb", type:"base"},
    {id:294, en:"Sleep", ta:"Thoongu", pron:"", cat:"Verb", type:"base"},
    {id:295, en:"Speak / Talk", ta:"Paesu", pron:"", cat:"Verb", type:"base"},
    {id:296, en:"Wash", ta:"Kaluvu", pron:"", cat:"Verb", type:"base"},
    {id:297, en:"Search", ta:"Thaedu", pron:"", cat:"Verb", type:"base"},
    {id:298, en:"Sing", ta:"Paadu", pron:"", cat:"Verb", type:"base"},
    {id:299, en:"Dance", ta:"Aadu", pron:"", cat:"Verb", type:"base"},
    {id:300, en:"Cook", ta:"Samai", pron:"", cat:"Verb", type:"base"},
    {id:301, en:"Come", ta:"Vaa", pron:"", cat:"Verb", type:"base"},
    {id:302, en:"Go", ta:"Poo", pron:"", cat:"Verb", type:"base"},

    // Additional Verbs (base forms)
    {id:305, en:"Lift", ta:"Thooku", pron:"", cat:"Verb", type:"base"},
    {id:306, en:"Send", ta:"Anupu", pron:"", cat:"Verb", type:"base"},
    {id:307, en:"Grab / Catch", ta:"Pudi", pron:"Pudi-ka-num", cat:"Verb", type:"base"},
    {id:308, en:"Swim", ta:"Neechal / Neendhirathu", pron:"", cat:"Verb", type:"base"},
    {id:309, en:"Visit", ta:"Varugai", pron:"", cat:"Verb", type:"base"},
    {id:310, en:"Play", ta:"Vilaiyadu", pron:"", cat:"Verb", type:"base"},
    {id:311, en:"Dream", ta:"Kanavu", pron:"", cat:"Verb", type:"base"},
    {id:312, en:"Ask", ta:"Kaelu", pron:"Kae-ka-num", cat:"Verb", type:"base"},
    {id:313, en:"Fight", ta:"Sandai", pron:"", cat:"Verb", type:"base"},
    {id:314, en:"Jump", ta:"Kuthi", pron:"", cat:"Verb", type:"base"},
    {id:315, en:"Drink", ta:"Kudi", pron:"", cat:"Verb", type:"base"},
    {id:316, en:"Read", ta:"Vaasi", pron:"", cat:"Verb", type:"base"},
    {id:317, en:"Turn", ta:"Thirumbu / Thirupu", pron:"", cat:"Verb", type:"base"},
    {id:318, en:"Throw", ta:"Veesu / Thooki Poodu", pron:"", cat:"Verb", type:"base"},
    {id:319, en:"Give", ta:"Thaa / Kudu", pron:"Thaara-num / Kuduka-num", cat:"Verb", type:"base"},
    {id:320, en:"Open", ta:"Thoora", pron:"Thooraka-num", cat:"Verb", type:"base"},
    {id:321, en:"Sit", ta:"Ootkaru", pron:"", cat:"Verb", type:"base"},
    {id:322, en:"Hug", ta:"Kattipudi", pron:"", cat:"Verb", type:"base"},
    {id:323, en:"Laugh", ta:"Siri", pron:"", cat:"Verb", type:"base"},
    {id:324, en:"Ride", ta:"Ootu", pron:"", cat:"Verb", type:"base"},
    {id:325, en:"Shake", ta:"Kulukku / Aatu", pron:"", cat:"Verb", type:"base"},
    {id:326, en:"Listen", ta:"Gavani", pron:"", cat:"Verb", type:"base"},
    {id:327, en:"Knit", ta:"Pinnu", pron:"", cat:"Verb", type:"base"},
    {id:328, en:"Buy", ta:"Vaangu", pron:"", cat:"Verb", type:"base"},
    {id:329, en:"Write", ta:"Yeluthu", pron:"", cat:"Verb", type:"base"},
    {id:330, en:"Walk", ta:"Nada", pron:"Nadaka-num", cat:"Verb", type:"base"},
    {id:331, en:"Smell", ta:"Mugarnthu", pron:"", cat:"Verb", type:"base"},
    {id:332, en:"Hear", ta:"Kaekutha", pron:"Kaekanum", cat:"Verb", type:"base"},
    {id:333, en:"Fall", ta:"Vilu", pron:"", cat:"Verb", type:"base"},
    {id:334, en:"Call", ta:"Koopidu", pron:"", cat:"Verb", type:"base"},
    {id:335, en:"Build", ta:"Kattu", pron:"", cat:"Verb", type:"base"},
    {id:336, en:"Help", ta:"Udhavu", pron:"", cat:"Verb", type:"base"},
    {id:337, en:"Hit", ta:"Adi", pron:"", cat:"Verb", type:"base"},
    {id:338, en:"Dig", ta:"Noondu", pron:"", cat:"Verb", type:"base"},
    {id:339, en:"Fix", ta:"Seri Sei", pron:"Seri Seiyanum", cat:"Verb", type:"base"},
    {id:340, en:"See", ta:"Paaru", pron:"Paarkanum", cat:"Verb", type:"base"},
    {id:341, en:"Run", ta:"Oodu", pron:"", cat:"Verb", type:"base"},
    {id:342, en:"Clap", ta:"Kai Thattu", pron:"", cat:"Verb", type:"base"},
    {id:343, en:"Grind", ta:"Arai", pron:"", cat:"Verb", type:"base"},
    {id:344, en:"Paint", ta:"Vannam Theetu", pron:"", cat:"Verb", type:"base"},
    {id:345, en:"Wait", ta:"Kaathiru", pron:"", cat:"Verb", type:"base"},
    {id:346, en:"Fly", ta:"Para", pron:"Parakanum", cat:"Verb", type:"base"},
    {id:347, en:"Race", ta:"Pooti / Pandhaiyam", pron:"", cat:"Verb", type:"base"},
    {id:348, en:"Close", ta:"Moodu", pron:"", cat:"Verb", type:"base"},
    {id:349, en:"Stand", ta:"Nillu", pron:"Nikka-num", cat:"Verb", type:"base"},
    {id:350, en:"Draw", ta:"Varai", pron:"Varaiya-num", cat:"Verb", type:"base"},
    {id:351, en:"Bath", ta:"Kuli", pron:"", cat:"Verb", type:"base"},
    {id:352, en:"Study", ta:"Padi", pron:"", cat:"Verb", type:"base"},
    {id:353, en:"Learn", ta:"Kathuko", pron:"", cat:"Verb", type:"base"},
    {id:354, en:"Show", ta:"Kaatu / Kaami", pron:"", cat:"Verb", type:"base"},
    {id:355, en:"Start", ta:"Aarambi / Thodangu", pron:"", cat:"Verb", type:"base"},
    {id:356, en:"Use", ta:"Ubaiyogi / Payanpaduthu", pron:"", cat:"Verb", type:"base"},
    {id:357, en:"Find", ta:"Kandu Pudi", pron:"", cat:"Verb", type:"base"},
    {id:358, en:"Pour", ta:"Oothu", pron:"", cat:"Verb", type:"base"},
    {id:359, en:"Clean", ta:"Sutham Sei", pron:"Seiyanum", cat:"Verb", type:"base"},
    {id:360, en:"Push", ta:"Thallu", pron:"", cat:"Verb", type:"base"},
    {id:361, en:"Pull", ta:"Illu", pron:"Illukanum", cat:"Verb", type:"base"},
    {id:362, en:"Move", ta:"Thallu", pron:"", cat:"Verb", type:"base"},
    {id:363, en:"Change", ta:"Maathu", pron:"", cat:"Verb", type:"base"},
    {id:364, en:"Touch", ta:"Thotu", pron:"", cat:"Verb", type:"base"},
    {id:365, en:"Share", ta:"Pagheeru", pron:"", cat:"Verb", type:"base"},
    {id:366, en:"Missing / Lose", ta:"Tholai", pron:"", cat:"Verb", type:"base"},
    {id:367, en:"Stay", ta:"Thangu", pron:"", cat:"Verb", type:"base"},
    {id:368, en:"Take", ta:"Yedu", pron:"Yedukanum", cat:"Verb", type:"base"},
    {id:369, en:"Put", ta:"Poodu", pron:"", cat:"Verb", type:"base"},
    {id:370, en:"Bear / Endure", ta:"Thaangu", pron:"", cat:"Verb", type:"base"},
    {id:371, en:"Pluck", ta:"Pudungu", pron:"", cat:"Verb", type:"base"},
    {id:372, en:"Stop", ta:"Niruthu", pron:"", cat:"Verb", type:"base"},
    {id:373, en:"Join", ta:"Seru", pron:"", cat:"Verb", type:"base"},
    {id:374, en:"Climb", ta:"Yaeru", pron:"", cat:"Verb", type:"base"},
    {id:375, en:"Think", ta:"Yosi", pron:"", cat:"Verb", type:"base"},
    {id:376, en:"Remember / Thought", ta:"Nenai", pron:"", cat:"Verb", type:"base"},
    {id:377, en:"Teach", ta:"Solli Kudu", pron:"Kudukanum", cat:"Verb", type:"base"},
    {id:378, en:"Kick", ta:"Udai", pron:"", cat:"Verb", type:"base"},
    {id:379, en:"Hang", ta:"Thongu", pron:"", cat:"Verb", type:"base"},
    {id:380, en:"Vacate / Empty", ta:"Kaali", pron:"", cat:"Verb", type:"base"},
    {id:381, en:"Leave", ta:"Vidu / Kelambu", pron:"", cat:"Verb", type:"base"},
    {id:382, en:"Bite", ta:"Kadi", pron:"", cat:"Verb", type:"base"},
    {id:383, en:"Brush", ta:"Valaku", pron:"", cat:"Verb", type:"base"},
    {id:384, en:"Comb", ta:"Seevu", pron:"", cat:"Verb", type:"base"},
    {id:385, en:"Count", ta:"Yennu", pron:"", cat:"Verb", type:"base"},
    {id:386, en:"Cut", ta:"Vettu", pron:"", cat:"Verb", type:"base"},
    {id:387, en:"Tie", ta:"Kattu", pron:"", cat:"Verb", type:"base"},
    {id:388, en:"Break", ta:"Odai", pron:"", cat:"Verb", type:"base"},
    {id:389, en:"Rub", ta:"Orai / Thaeyi", pron:"", cat:"Verb", type:"base"},
    {id:390, en:"Yawn", ta:"Kottavi", pron:"", cat:"Verb", type:"base"},
    {id:391, en:"Measure", ta:"Aalavu", pron:"", cat:"Verb", type:"base"},
    {id:392, en:"Screw", ta:"Thiruku", pron:"", cat:"Verb", type:"base"},
    {id:393, en:"Keep", ta:"Vei", pron:"", cat:"Verb", type:"base"},
    {id:394, en:"Wake up / Get up", ta:"Yendhiri", pron:"", cat:"Verb", type:"base"},
    {id:395, en:"Sweep", ta:"Kootu", pron:"", cat:"Verb", type:"base"},
    {id:396, en:"Scribble", ta:"Kirukku", pron:"", cat:"Verb", type:"base"},
    {id:397, en:"Chase", ta:"Thoorathu", pron:"", cat:"Verb", type:"base"},
    {id:398, en:"Cry", ta:"Aalu", pron:"Aalukanum", cat:"Verb", type:"base"},
    {id:399, en:"Decide", ta:"Mudivu Pannu", pron:"", cat:"Verb", type:"base"},
    {id:400, en:"Burn", ta:"Yaeri", pron:"", cat:"Verb", type:"base"},
    {id:401, en:"Grow", ta:"Valar", pron:"Valaranum / Valarkanum", cat:"Verb", type:"base"},
    {id:402, en:"Admire", ta:"Rasi", pron:"", cat:"Verb", type:"base"},
    {id:403, en:"Return", ta:"Thirupi Kudu", pron:"", cat:"Verb", type:"base"},

    // Adjectives
    {id:303, en:"Favourite", ta:"Pudicha", pron:"", cat:"Adjective"},
    {id:304, en:"Fear", ta:"Bayam", pron:"", cat:"Abstract"},

    // New words
    {id:404, en:"Difficult", ta:"Kashtam", pron:"", cat:"Adjective"},
    {id:405, en:"Sunny", ta:"Vaeyil", pron:"", cat:"Adjective"},
    {id:406, en:"Half", ta:"Paathi", pron:"", cat:"Adjective"},
    {id:407, en:"Left over", ta:"Methi", pron:"", cat:"Adjective"},
    {id:408, en:"Near to home", ta:"Veetu-kitta", pron:"", cat:"Location"},
    {id:409, en:"Clothes", ta:"Thuni", pron:"", cat:"Noun"},
    {id:410, en:"Daily", ta:"Dhinamum", pron:"", cat:"Adverb/Time"},
    {id:411, en:"If there is / If it's there", ta:"Irundha", pron:"", cat:"Connector"},
    {id:412, en:"Same", ta:"Orae Mathiri", pron:"", cat:"Adjective"},
    {id:413, en:"What else", ta:"Vera Yenna", pron:"", cat:"Question Word"},
    {id:414, en:"Frequent / Often", ta:"Adikadi", pron:"", cat:"Adverb/Time"},
    {id:415, en:"Few times / Sometimes", ta:"Sila Thavada", pron:"", cat:"Adverb/Time"},
    {id:416, en:"In a year", ta:"Varushathula", pron:"", cat:"Adverb/Time"},
    {id:417, en:"This much", ta:"Ivlo", pron:"", cat:"Adjective"},
    {id:418, en:"Till / Still", ta:"Innum", pron:"", cat:"Connector"},
    {id:419, en:"Won't be / Don't be", ta:"Irukathu", pron:"", cat:"Verb", type:"base"},
    {id:420, en:"Sometimes", ta:"Eppaiyavathu", pron:"", cat:"Adverb/Time"},
    {id:421, en:"Always", ta:"Eppaiyumae", pron:"", cat:"Adverb/Time"},
    {id:422, en:"Forgot", ta:"Maranthu", pron:"", cat:"Verb", type:"base"},
    {id:423, en:"It's okay", ta:"Paravala", pron:"", cat:"Abstract"},
    {id:424, en:"Can you?", ta:"Mudiyuma?", pron:"", cat:"Question Word"},
    {id:425, en:"Is it? / Like that?", ta:"Appadiya?", pron:"", cat:"Question Word"},
    {id:426, en:"Like this?", ta:"Ippadiya?", pron:"", cat:"Question Word"},
    {id:427, en:"All / Everything", ta:"Ellam", pron:"", cat:"Pronoun"},
    {id:428, en:"Everyone", ta:"Ellarum", pron:"", cat:"Pronoun"},
    {id:429, en:"Should be", ta:"Irukanum", pron:"", cat:"Verb", type:"base"},
    {id:430, en:"Could be", ta:"Irukalam", pron:"", cat:"Verb", type:"base"},
    {id:431, en:"May be", ta:"Irudhalum Irukalam / Irukum", pron:"", cat:"Verb", type:"base"},
    {id:432, en:"Don't need", ta:"Thaevai Illa", pron:"", cat:"Abstract"},
    {id:433, en:"Need", ta:"Thaevai Iruku", pron:"", cat:"Abstract"},
    {id:434, en:"Head", ta:"Thalai", pron:"", cat:"Noun"},
    {id:435, en:"Hair", ta:"Mudi", pron:"", cat:"Noun"},
    {id:436, en:"Water", ta:"Thanni", pron:"", cat:"Noun"},
    {id:437, en:"Nothing", ta:"Onnumae Illa", pron:"", cat:"Abstract"},
    {id:438, en:"No one", ta:"Yaarumae", pron:"", cat:"Pronoun"},
    {id:439, en:"Until / Till", ta:"Varaikum", pron:"", cat:"Connector"},
    {id:440, en:"30", ta:"Moopathu", pron:"", cat:"Number"},
    {id:441, en:"Rain / Mountain", ta:"Malai", pron:"", cat:"Noun"},
    {id:442, en:"Last month", ta:"Ponna Maasam", pron:"", cat:"Adverb/Time"},
    {id:443, en:"If not", ta:"Ilana", pron:"", cat:"Connector"},
    {id:444, en:"Soon / Quick", ta:"Seikaram", pron:"", cat:"Adverb"},
    {id:445, en:"Small / Kid", ta:"Kutty", pron:"", cat:"Adjective"}
];

// Opposite pairs for matching game
// Total: 15 pairs
const oppositePairs = [
    [1, 4],     // Morning - Night
    [111, 112], // Up - Down
    [113, 114], // Front - Back
    [115, 116], // Small - Big
    [117, 118], // Less - More
    [120, 121], // This - That
    [122, 123], // Here - There
    [124, 125], // Now - Then
    [128, 129], // Truth - Lie
    [130, 131], // Right - Wrong
    [132, 133], // Bitter - Sweet
    [138, 139], // Inside - Outside
    [140, 141], // Old - New
    [142, 144], // Yesterday - Tomorrow
    [148, 149]  // Yes - No
];

// Complete sentence pairs for fill-in-the-blank exercises
// Inspired by Tamil children's books with natural, grammatically correct sentences
// All use romanized Tamil (no Tamil script)
const sentencePairs = [
    // EASY - Greetings & Daily Routines (10 sentences)
    {
        id: 1,
        english: "Good morning, how are you?",
        tamil: "Kaalai vanakkam, neenga eppadi irukeenga?",
        blanks: ["Kaalai vanakkam"],
        blankEnglish: {"Kaalai vanakkam": "Good morning"},
        hint: "Kaa-lai va-nak-kam",
        highlight: ["eppadi", "irukeenga"],
        difficulty: "easy"
    },
    {
        id: 2,
        english: "I woke up in the morning",
        tamil: "Naan kaalai-la elundhiruchen",
        blanks: ["kaalai-la"],
        blankEnglish: {"kaalai-la": "in the morning"},
        hint: "morning + in (la suffix)",
        highlight: ["elundhiruchen"],
        difficulty: "easy"
    },
    {
        id: 3,
        english: "Grandma cooked breakfast",
        tamil: "Paati kaalai saapadu samaichchanga",
        blanks: ["kaalai saapadu"],
        blankEnglish: {"kaalai saapadu": "breakfast"},
        hint: "Kaa-lai saa-pa-du",
        highlight: ["samaichchanga"],
        difficulty: "easy"
    },
    {
        id: 4,
        english: "I drink milk in the morning",
        tamil: "Naan kaalai-la paal kudikuren",
        blanks: ["paal"],
        blankEnglish: {"paal": "milk"},
        hint: "milk",
        highlight: ["kudikuren"],
        difficulty: "easy"
    },
    {
        id: 5,
        english: "Good night, see you tomorrow",
        tamil: "Rathiri vanakkam, naalaiku paakalam",
        blanks: ["Rathiri vanakkam"],
        blankEnglish: {"Rathiri vanakkam": "Good night"},
        hint: "Raa-thri va-nak-kam",
        highlight: ["paakalam"],
        difficulty: "easy"
    },
    {
        id: 6,
        english: "Today is a good day",
        tamil: "Inaiku nalla naal",
        blanks: ["Inaiku"],
        blankEnglish: {"Inaiku": "Today"},
        hint: "today",
        highlight: ["naal"],
        difficulty: "easy"
    },
    {
        id: 7,
        english: "I am going home now",
        tamil: "Naan ippo veetuku poren",
        blanks: ["veetuku"],
        blankEnglish: {"veetuku": "home"},
        hint: "veetu + ku (to suffix)",
        highlight: ["poren"],
        difficulty: "easy"
    },
    {
        id: 8,
        english: "My name is good",
        tamil: "En peru nalladu",
        blanks: ["peru"],
        blankEnglish: {"peru": "name"},
        hint: "name/person",
        highlight: ["nalladu"],
        difficulty: "easy"
    },
    {
        id: 9,
        english: "Where is the house?",
        tamil: "Veedu yenga iruku?",
        blanks: ["yenga"],
        blankEnglish: {"yenga": "Where"},
        hint: "where",
        highlight: ["iruku"],
        difficulty: "easy"
    },
    {
        id: 10,
        english: "Yes, I like it very much",
        tamil: "Aama, enaku romba pudikum",
        blanks: ["Aama"],
        blankEnglish: {"Aama": "Yes"},
        hint: "yes",
        highlight: ["enaku", "pudikum"],
        difficulty: "easy"
    },

    // EASY-MEDIUM - Family & Relationships (10 sentences)
    {
        id: 11,
        english: "My father is at home",
        tamil: "En appa veetla irukaru",
        blanks: ["appa"],
        blankEnglish: {"appa": "father"},
        hint: "father",
        highlight: ["veetla", "irukaru"],
        difficulty: "easy"
    },
    {
        id: 12,
        english: "Mother is cooking food",
        tamil: "Amma saapadu samaikuranga",
        blanks: ["Amma"],
        blankEnglish: {"Amma": "Mother"},
        hint: "mother",
        highlight: ["saapadu", "samaikuranga"],
        difficulty: "easy"
    },
    {
        id: 13,
        english: "Grandma tells me stories",
        tamil: "Paati enaku kadhai solluvaanga",
        blanks: ["Paati"],
        blankEnglish: {"Paati": "Grandma"},
        hint: "grandmother",
        highlight: ["kadhai", "solluvaanga"],
        difficulty: "easy"
    },
    {
        id: 14,
        english: "I play with my older brother",
        tamil: "Naan en anna kuda vilayaaduren",
        blanks: ["anna"],
        blankEnglish: {"anna": "older brother"},
        hint: "older brother",
        highlight: ["kuda", "vilayaaduren"],
        difficulty: "easy"
    },
    {
        id: 15,
        english: "My older sister is very beautiful",
        tamil: "En akka romba azhaga irukanga",
        blanks: ["akka"],
        blankEnglish: {"akka": "older sister"},
        hint: "older sister",
        highlight: ["azhaga", "irukanga"],
        difficulty: "easy"
    },
    {
        id: 16,
        english: "Younger brother came to the house",
        tamil: "Thumbi veetuku vandhaan",
        blanks: ["Thumbi"],
        blankEnglish: {"Thumbi": "Younger brother"},
        hint: "younger brother",
        highlight: ["veetuku", "vandhaan"],
        difficulty: "medium"
    },
    {
        id: 17,
        english: "Uncle is a good person",
        tamil: "Mama nalla per",
        blanks: ["Mama"],
        blankEnglish: {"Mama": "Uncle"},
        hint: "uncle",
        highlight: ["nalla", "per"],
        difficulty: "easy"
    },
    {
        id: 18,
        english: "My house is very big",
        tamil: "En veedu romba periya",
        blanks: ["En"],
        blankEnglish: {"En": "My"},
        hint: "my",
        highlight: ["veedu", "periya"],
        difficulty: "easy"
    },
    {
        id: 19,
        english: "Your house is here, my house is there",
        tamil: "Unga veedu inga, en veedu anga",
        blanks: ["Unga"],
        blankEnglish: {"Unga": "Your"},
        hint: "your",
        highlight: ["veedu", "inga", "anga"],
        difficulty: "easy"
    },
    {
        id: 20,
        english: "Our family is happy",
        tamil: "Namma kudumbam sandhoshamaa iruku",
        blanks: ["Namma"],
        blankEnglish: {"Namma": "Our"},
        hint: "our (inclusive)",
        highlight: ["kudumbam", "sandhoshamaa"],
        difficulty: "medium"
    },

    // MEDIUM - Locations & Directions (10 sentences)
    {
        id: 21,
        english: "The book is on the table",
        tamil: "Pusthagam meja maela iruku",
        blanks: ["maela"],
        blankEnglish: {"maela": "on"},
        hint: "on/above",
        highlight: ["Pusthagam", "meja"],
        difficulty: "medium"
    },
    {
        id: 22,
        english: "The cat is under the bed",
        tamil: "Poonai kattil keezha iruku",
        blanks: ["keezha"],
        blankEnglish: {"keezha": "under"},
        hint: "under/below",
        highlight: ["Poonai", "kattil"],
        difficulty: "medium"
    },
    {
        id: 23,
        english: "I am standing in front of the house",
        tamil: "Naan veedu munnadi ninnutruken",
        blanks: ["munnadi"],
        blankEnglish: {"munnadi": "in front of"},
        hint: "in front",
        highlight: ["ninnutruken"],
        difficulty: "medium"
    },
    {
        id: 24,
        english: "The garden is behind the house",
        tamil: "Thotham veedu pinnadi iruku",
        blanks: ["pinnadi"],
        blankEnglish: {"pinnadi": "behind"},
        hint: "behind",
        highlight: ["Thotham", "veedu"],
        difficulty: "medium"
    },
    {
        id: 25,
        english: "Come here, don't go there",
        tamil: "Inga vaa, anga pogaadhe",
        blanks: ["inga"],
        blankEnglish: {"inga": "here"},
        hint: "here",
        highlight: ["vaa", "pogaadhe"],
        difficulty: "medium"
    },
    {
        id: 26,
        english: "I am inside the house",
        tamil: "Naan veedu ulla iruken",
        blanks: ["ulla"],
        blankEnglish: {"ulla": "inside"},
        hint: "inside",
        highlight: ["veedu", "iruken"],
        difficulty: "medium"
    },
    {
        id: 27,
        english: "The children are playing outside",
        tamil: "Pasanga veliya vilayaadranga",
        blanks: ["veliya"],
        blankEnglish: {"veliya": "outside"},
        hint: "outside",
        highlight: ["Pasanga", "vilayaadranga"],
        difficulty: "medium"
    },
    {
        id: 28,
        english: "This is small, that is big",
        tamil: "Idhu chinna, adhu periya",
        blanks: ["chinna"],
        blankEnglish: {"chinna": "small"},
        hint: "small",
        highlight: ["periya"],
        difficulty: "medium"
    },
    {
        id: 29,
        english: "I want a little food, not too much",
        tamil: "Enaku konjam saapadu venum, romba vendam",
        blanks: ["konjam"],
        blankEnglish: {"konjam": "a little"},
        hint: "a little",
        highlight: ["venum", "vendam"],
        difficulty: "medium"
    },
    {
        id: 30,
        english: "There are many people here",
        tamil: "Inga neraiya per irukanga",
        blanks: ["neraiya"],
        blankEnglish: {"neraiya": "many"},
        hint: "many/a lot",
        highlight: ["per", "irukanga"],
        difficulty: "medium"
    },

    // MEDIUM - Time & When (8 sentences)
    {
        id: 31,
        english: "I ate food yesterday",
        tamil: "Naan nethu saapadu saapten",
        blanks: ["nethu"],
        blankEnglish: {"nethu": "yesterday"},
        hint: "yesterday",
        highlight: ["saapadu", "saapten"],
        difficulty: "medium"
    },
    {
        id: 32,
        english: "Tomorrow I will go to school",
        tamil: "Naalaiku naan schoolku poven",
        blanks: ["Naalaiku"],
        blankEnglish: {"Naalaiku": "Tomorrow"},
        hint: "tomorrow",
        highlight: ["schoolku", "poven"],
        difficulty: "medium"
    },
    {
        id: 33,
        english: "I saw mother yesterday",
        tamil: "Naan nethu amma-va paarthen",
        blanks: ["nethu"],
        blankEnglish: {"nethu": "yesterday"},
        hint: "yesterday",
        highlight: ["amma-va", "paarthen"],
        difficulty: "medium"
    },
    {
        id: 34,
        english: "We worked hard last week",
        tamil: "Naanga ponna vaaram kashtappattom",
        blanks: ["ponna vaaram"],
        blankEnglish: {"ponna vaaram": "last week"},
        hint: "last week",
        highlight: ["kashtappattom"],
        difficulty: "medium"
    },
    {
        id: 35,
        english: "I will sleep at 9 o'clock",
        tamil: "Naan onbathu mani neramukku thoonguven",
        blanks: ["onbathu"],
        blankEnglish: {"onbathu": "nine"},
        hint: "nine (9)",
        highlight: ["mani", "thoonguven"],
        difficulty: "medium"
    },
    {
        id: 36,
        english: "In the month of January it's cold",
        tamil: "January maasam-la kuliraa irukum",
        blanks: ["maasam-la"],
        blankEnglish: {"maasam-la": "in the month"},
        hint: "month + in (la suffix)",
        highlight: ["kuliraa", "irukum"],
        difficulty: "medium"
    },
    {
        id: 37,
        english: "One day, a bird came",
        tamil: "Oru naal, oru kuruvi vandhudhu",
        blanks: ["Oru naal"],
        blankEnglish: {"Oru naal": "One day"},
        hint: "one day",
        highlight: ["kuruvi", "vandhudhu"],
        difficulty: "medium"
    },
    {
        id: 38,
        english: "Now I understand, before I didn't know",
        tamil: "Ippo enaku puriyuthu, munnaadi theriyala",
        blanks: ["Ippo"],
        blankEnglish: {"Ippo": "Now"},
        hint: "now",
        highlight: ["puriyuthu", "theriyala"],
        difficulty: "medium"
    },

    // MEDIUM-HARD - Feelings & Descriptions (8 sentences)
    {
        id: 39,
        english: "This food is very sweet",
        tamil: "Indha saapadu romba inipu",
        blanks: ["inipu"],
        blankEnglish: {"inipu": "sweet"},
        hint: "sweet",
        highlight: ["saapadu"],
        difficulty: "medium"
    },
    {
        id: 40,
        english: "The curry is very spicy",
        tamil: "Kuzhambu romba kaaram",
        blanks: ["kaaram"],
        blankEnglish: {"kaaram": "spicy"},
        hint: "spicy",
        highlight: ["Kuzhambu"],
        difficulty: "medium"
    },
    {
        id: 41,
        english: "I like sour taste",
        tamil: "Enaku pulipu pudikum",
        blanks: ["pulipu"],
        blankEnglish: {"pulipu": "sour"},
        hint: "sour",
        highlight: ["pudikum"],
        difficulty: "medium"
    },
    {
        id: 42,
        english: "This is old, that is new",
        tamil: "Idhu palaya, adhu pudhusu",
        blanks: ["palaya"],
        blankEnglish: {"palaya": "old"},
        hint: "old",
        highlight: ["pudhusu"],
        difficulty: "medium"
    },
    {
        id: 43,
        english: "That is correct, this is wrong",
        tamil: "Adhu sari, idhu thappu",
        blanks: ["sari"],
        blankEnglish: {"sari": "correct"},
        hint: "correct/right",
        highlight: ["thappu"],
        difficulty: "medium"
    },
    {
        id: 44,
        english: "Tell the truth, don't tell lies",
        tamil: "Unmai sollu, poi sollaaadhe",
        blanks: ["Unmai"],
        blankEnglish: {"Unmai": "truth"},
        hint: "truth",
        highlight: ["sollu", "poi", "sollaaadhe"],
        difficulty: "hard"
    },
    {
        id: 45,
        english: "I am hungry, please give me food",
        tamil: "Enaku pasikkuthu, please saapadu kudunga",
        blanks: ["pasikkuthu"],
        blankEnglish: {"pasikkuthu": "hungry"},
        hint: "hungry (to me)",
        highlight: ["kudunga"],
        difficulty: "hard"
    },
    {
        id: 46,
        english: "This is enough, I don't want more",
        tamil: "Idhu podhum, enaku adhigam vendam",
        blanks: ["podhum"],
        blankEnglish: {"podhum": "enough"},
        hint: "enough",
        highlight: ["adhigam", "vendam"],
        difficulty: "hard"
    },

    // HARD - Questions & Complex Sentences (6 sentences)
    {
        id: 47,
        english: "Who is that person?",
        tamil: "Andha per yaaru?",
        blanks: ["yaaru"],
        blankEnglish: {"yaaru": "Who"},
        hint: "who",
        highlight: ["per"],
        difficulty: "hard"
    },
    {
        id: 48,
        english: "Why did this happen?",
        tamil: "Idhu yaen aayiduchu?",
        blanks: ["yaen"],
        blankEnglish: {"yaen": "Why"},
        hint: "why",
        highlight: ["aayiduchu"],
        difficulty: "hard"
    },
    {
        id: 49,
        english: "How do you do this?",
        tamil: "Neenga idha eppadi seiringa?",
        blanks: ["eppadi"],
        blankEnglish: {"eppadi": "How"},
        hint: "how",
        highlight: ["seiringa"],
        difficulty: "hard"
    },
    {
        id: 50,
        english: "Do you understand? Yes, I understand",
        tamil: "Ungaluku puriyutha? Aama, enaku puriyuthu",
        blanks: ["puriyuthu"],
        blankEnglish: {"puriyuthu": "understand"},
        hint: "understand (to me)",
        highlight: ["Ungaluku", "puriyutha"],
        difficulty: "hard"
    }
];
